/*==========================================================================
   RAPIDFEET — Product Catalog
==========================================================================*/

const RF_BRANDS = [
  "Adidas",
  "Nike",
  "PUMA",
  "Vans",
  "Converse",
  "New Balance",
  "MLB",
];

const RF_COLORS = {
  "Jet Black": "#0D0D0D",
  "Cloud White": "#FAFAF8",
  "Ember Orange": "#FF5A1F",
  "Volt Purple": "#6B4EFF",
  "Slate Grey": "#6E6E6E",
  "Forest Green": "#2C5F3F",
  Sand: "#D8C7A8",
  Crimson: "#B3261E",
  Navy: "#1B2A4A",
  "Sky Blue": "#7EC8E3",
  Gold: "#D4AF37",
  Pink: "#F2A6C1",
  Brown: "#5C4332",
};

const RF_CATEGORIES = ["Running", "Lifestyle", "Basketball"];

function rfImg(seed, w = 600, h = 600) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

const RF_PRODUCTS = [
  {
    id: "P1000",
    name: "Adidas Forum Low CL 'Off White'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: 3250000,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.0,
    reviews: 8,
    isNew: false,
    onSale: true,
    stock: 0,
    gender: "Women",
    image: "assets/Adidas Forum Low CL ‘Off White’/1.jpg",
    gallery: [
      "assets/Adidas Forum Low CL ‘Off White’/1.jpg",
      "assets/Adidas Forum Low CL ‘Off White’/2.jpg",
      "assets/Adidas Forum Low CL ‘Off White’/3.jpg",
      "assets/Adidas Forum Low CL ‘Off White’/4.jpg",
    ],
    description_en:
      "The Adidas Forum Low CL 'Off White' from Adidas is crafted from premium synthetic leather, built for everyday wear with a clean, versatile silhouette in Off White.",
    description_vi:
      "Giày Adidas Forum Low CL 'Off White' làm từ chất liệu da tổng hợp cao cấp, giữ phom dáng ôm chân thoải mái. Phối màu trắng ngà thanh lịch, trang nhã cùng quai dán đặc trưng và đế cao su bền bỉ mang đến một biểu tượng thời trang đường phố tối giản, cao cấp",
    sku: "RF-1000-ADI",
    material: "Da tổng hợp cao cấp",
  },

  {
    id: "P1001",
    name: "Adidas originals Stan Smith 'Cloud White Gold'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.7,
    reviews: 31,
    isNew: false,
    onSale: false,
    stock: 15,
    gender: "Men",
    image: "assets/Adidas originals Stan Smith ‘Cloud White Gold’/1.jpg",
    gallery: [
      "assets/Adidas originals Stan Smith ‘Cloud White Gold’/1.jpg",
      "assets/Adidas originals Stan Smith ‘Cloud White Gold’/2.avif",
      "assets/Adidas originals Stan Smith ‘Cloud White Gold’/3.avif",
      "assets/Adidas originals Stan Smith ‘Cloud White Gold’/4.avif",
    ],
    description_en:
      "The Adidas originals Stan Smith 'Cloud White Gold' from Adidas is crafted from genuine leather, built for everyday wear with a clean, versatile silhouette in Cloud White.",
    description_vi:
      "Phiên bản đặc biệt của dòng Stan Smith với chất liệu da thật cao cấp phối cùng đế cao su bám đường tốt. Thiết kế mang màu trắng tinh khiết kết hợp các chi tiết logo viền vàng Gold sang trọng ở lưỡi và gót giày, tạo nên vẻ ngoài cổ điển đầy cao cấp. Đây là một biểu tượng thời trang đường phố mang đậm dấu ấn lịch sử của Adidas, phù hợp cho cả nam và nữ yêu thích phong cách thể thao cổ điển.",
    sku: "RF-1001-ADI",
    material: "Da thật",
  },

  {
    id: "P1002",
    name: "Adidas Samba JP 'Collegiate Green'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 3000000,
    oldPrice: null,
    colors: ["Forest Green", "Slate Grey"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.4,
    reviews: 54,
    isNew: false,
    onSale: false,
    stock: 18,
    gender: "Unisex",
    image: "assets/Adidas Samba JP ‘Collegiate Green’/1.jpg",
    gallery: [
      "assets/Adidas Samba JP ‘Collegiate Green’/1.jpg",
      "assets/Adidas Samba JP ‘Collegiate Green’/2.png",
      "assets/Adidas Samba JP ‘Collegiate Green’/3.png",
    ],
    description_en:
      "The Adidas Samba JP 'Collegiate Green' from Adidas is crafted from suede, built for everyday wear with a clean, versatile silhouette in White/Green.",
    description_vi:
      "Mẫu giày kết hợp độc đáo giữa phong cách retro châu Âu và thẩm mỹ tối giản của Nhật Bản. Thân giày làm bằng da lộn mềm mịn, nhấn nhá bằng logo 3 sọc da trơn, logo Samba ánh kim cùng đế cao su màu gum hoài cổ đầy chỉn chu, tinh tế. Thiết kế unisex với màu xanh lá cây đậm kết hợp trắng, tạo nên vẻ ngoài vừa cổ điển vừa hiện đại, phù hợp cho cả nam và nữ yêu thích phong cách thể thao cổ điển.",
    sku: "RF-1002-ADI",
    material: "Da lộn",
  },
  {
    id: "P1003",
    name: "Adidas Samba OG 'Cloud White Light Blue'",
    brand: "Adidas",
    category: "Running",
    price: 3290000,
    oldPrice: null,
    colors: ["Cloud White", "Sky Blue"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.1,
    reviews: 77,
    isNew: false,
    onSale: false,
    stock: 21,
    gender: "Women",
    image: "assets/Adidas Samba OG ‘Cloud White Light Blue’/1.jpg",
    gallery: [
      "assets/Adidas Samba OG ‘Cloud White Light Blue’/1.jpg",
      "assets/Adidas Samba OG ‘Cloud White Light Blue’/2.avif",
      "assets/Adidas Samba OG ‘Cloud White Light Blue’/3.avif",
      "assets/Adidas Samba OG ‘Cloud White Light Blue’/4.jpg",
    ],
    description_en:
      "The Adidas Samba OG 'Cloud White Light Blue' from Adidas is crafted from leather, mesh, and suede, built for everyday wear with a clean, versatile silhouette in Cloud White/Light Blue.",
    description_vi:
      "Thiết kế retro mang phong cách thể thao cổ điển pha chút hiện đại. Sự phối hợp tinh tế giữa nền da cao cấp màu trắng nhạt, các chi tiết da lộn màu xanh nhạt tươi mới, lớp đệm truyền thống êm ái cùng đế ngoài cao su rãnh sâu chống trơn trượt.",
    sku: "RF-1003-ADI",
    material: "Da/Vải lưới/Da lộn",
  },

  {
    id: "P1004",
    name: "Adidas Superstar II 'Cloud White'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: 3250000,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.8,
    reviews: 100,
    isNew: false,
    onSale: true,
    stock: 24,
    gender: "Men",
    image: "assets/Adidas Superstar II 'Cloud White'/1.jpg",
    gallery: [
      "assets/Adidas Superstar II 'Cloud White'/1.jpg",
      "assets/Adidas Superstar II 'Cloud White'/2.jpg",
      "assets/Adidas Superstar II 'Cloud White'/3.jpg",
      "assets/Adidas Superstar II 'Cloud White'/4.jpg",
    ],
    description_en:
      "The Adidas Superstar II 'Cloud White' from Adidas is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Black.",
    description_vi:
      "Phiên bản nâng cấp thời thượng từ dòng Superstar huyền thoại làm bằng da tổng hợp cao cấp dễ vệ sinh. Giữ nguyên thiết kế mũi vỏ sò bảo vệ ngón chân, ba sọc nổi bật và phối màu trắng mây tinh tế, dễ dàng phối hợp với mọi trang phục casual.",
    sku: "RF-1004-ADI",
    material: "Da cao cấp",
  },

  {
    id: "P1005",
    name: "Adidas Yeezy Boost 380 'Azure Non-Reflective'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 7900000,
    oldPrice: null,
    colors: ["Sky Blue", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.5,
    reviews: 123,
    isNew: false,
    onSale: false,
    stock: 27,
    gender: "Unisex",
    image: "assets/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/1.png",
    gallery: [
      "assets/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/1.png",
      "assets/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/2.png",
      "assets/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/3.png",
      "assets/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/4.png",
    ],
    description_en:
      "The Adidas Yeezy Boost 380 'Azure Non-Reflective' from Adidas is crafted from Primeknit, built for everyday wear with a clean, versatile silhouette in Light Blue.",
    description_vi:
      "Giày cổ thấp ôm chân làm từ chất liệu Primeknit dệt kim liền mạch, thoáng khí với sắc xanh lam nhạt trẻ trung và sọc cam cá tính. Trang bị đế giữa công nghệ Boost tiên tiến siêu đàn hồi và không có chi tiết phản quang, hướng tới sự đơn giản.",
    sku: "RF-1005-ADI",
    material: "Primeknit",
  },

  {
    id: "P1006",
    name: "Converse Aeon Active CX OX 'Egret'",
    brand: "Converse",
    category: "Running",
    price: 1890000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.2,
    reviews: 146,
    isNew: true,
    onSale: false,
    stock: 30,
    gender: "Women",
    image: "assets/Converse Aeon Active CX OX ‘Egret’/1.png",
    gallery: [
      "assets/Converse Aeon Active CX OX ‘Egret’/1.png",
      "assets/Converse Aeon Active CX OX ‘Egret’/2.png",
      "assets/Converse Aeon Active CX OX ‘Egret’/3.png",
      "assets/Converse Aeon Active CX OX ‘Egret’/4.png",
    ],
    description_en:
      "The Converse Aeon Active CX OX 'Egret' from Converse is crafted from synthetic leather and mesh, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Kiểu dáng low-top hiện đại mang phối màu trắng ngà thanh lịch lấy cảm hứng từ thiên nhiên. Thân giày kết hợp da tổng hợp và vải lưới thoáng khí, đi cùng logo Converse Star tinh tế, đế giữa CX đàn hồi và đế ngoài cao su chống trượt.",
    sku: "RF-1006-CON",
    material: "Da tổng hợp và vải lưới",
  },

  {
    id: "P1007",
    name: "Converse Chuck 70 Tortoise 'Black'",
    brand: "Converse",
    category: "Lifestyle",
    price: 1390000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.9,
    reviews: 169,
    isNew: false,
    onSale: false,
    stock: 4,
    gender: "Men",
    image: "assets/Converse Chuck 70 Tortoise 'Black'/1.jpg",
    gallery: [
      "assets/Converse Chuck 70 Tortoise 'Black'/1.jpg",
      "assets/Converse Chuck 70 Tortoise 'Black'/2.jpg",
      "assets/Converse Chuck 70 Tortoise 'Black'/3.jpg",
      "assets/Converse Chuck 70 Tortoise 'Black'/4.jpg",
    ],
    description_en:
      "The Converse Chuck 70 Tortoise 'Black' from Converse is crafted from canvas, built for everyday wear with a clean, versatile silhouette in White/Black.",
    description_vi:
      "Sự giao thoa giữa nét cổ điển và hiện đại với chất liệu vải canvas bền bỉ phối da tổng hợp. Giày mang sắc đen tối giản chủ đạo, tạo điểm nhấn phá cách bằng họa tiết vỏ rùa (tortoise) độc đáo, hệ thống đệm êm ái cùng đế cao su bám đường ổn định.",
    sku: "RF-1007-CON",
    material: "Canvas",
  },
  {
    id: "P1008",
    name: "Converse Chuck Taylor All Star Cruise OX 'Black White'",
    brand: "Converse",
    category: "Lifestyle",
    price: 1800000,
    oldPrice: 2250000,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.6,
    reviews: 192,
    isNew: false,
    onSale: true,
    stock: 36,
    gender: "Unisex",
    image:
      "assets/Converse Chuck Taylor All Star Cruise OX ‘Black White’/1.jpg",
    gallery: [
      "assets/Converse Chuck Taylor All Star Cruise OX ‘Black White’/1.jpg",
      "assets/Converse Chuck Taylor All Star Cruise OX ‘Black White’/2.jpg",
      "assets/Converse Chuck Taylor All Star Cruise OX ‘Black White’/3.jpg",
      "assets/Converse Chuck Taylor All Star Cruise OX ‘Black White’/4.jpg",
    ],
    description_en:
      "The Converse Chuck Taylor All Star Cruise OX 'Black White' from Converse is crafted from canvas fabric, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Phiên bản năng động từ dòng Chuck Taylor cổ điển với chất liệu vải canvas chất lượng cao thoáng khí. Thiết kế tương phản đen-trắng dễ phối đồ, kết hợp lót giày cải tiến tăng độ êm ái và đế cao su hoa văn chữ H bền bỉ.",
    sku: "RF-1008-CON",
    material: "Vải canvas",
  },

  {
    id: "P1009",
    name: "Converse Run Star Hike Low 'Black Gum'",
    brand: "Converse",
    category: "Lifestyle",
    price: 2700000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.3,
    reviews: 215,
    isNew: false,
    onSale: false,
    stock: 39,
    gender: "Women",
    image: "assets/Converse Run Star Hike Low 'Black Gum'/1.png",
    gallery: [
      "assets/Converse Run Star Hike Low 'Black Gum'/1.png",
      "assets/Converse Run Star Hike Low 'Black Gum'/2.png",
      "assets/Converse Run Star Hike Low 'Black Gum'/3.png",
      "assets/Converse Run Star Hike Low 'Black Gum'/4.png",
    ],
    description_en:
      "The Converse Run Star Hike Low 'Black Gum' from Converse is crafted from a full-grain leather upper with rugged suede details and metallic gold shimmer, built for everyday wear with a clean, versatile silhouette in Cloud White.",
    description_vi:
      "Bản cập nhật đầy táo bạo cho phom dáng Chuck 70 truyền thống bằng cách thêm lớp đệm TPU trong suốt bảo vệ hai bên và mặt sau. Thiết kế sở hữu các khoen kim loại lấy cảm hứng từ giày leo núi cùng phần đế giữa phóng đại, gồ ghề và phá cách.",
    sku: "RF-1009-CON",
    material:
      "Thân giày bằng da cật với các chi tiết da lộn bụi bặm và nhũ vàng ánh kim",
  },

  {
    id: "P1010",
    name: "MLB BigBall Chunky Embo NY Yankees",
    brand: "MLB",
    category: "Lifestyle",
    price: 4300000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.0,
    reviews: 238,
    isNew: false,
    onSale: false,
    stock: 42,
    gender: "Men",
    image: "assets/MLB BigBall Chunky Embo NY Yankees/1.png",
    gallery: [
      "assets/MLB BigBall Chunky Embo NY Yankees/1.png",
      "assets/MLB BigBall Chunky Embo NY Yankees/2.png",
      "assets/MLB BigBall Chunky Embo NY Yankees/3.png",
      "assets/MLB BigBall Chunky Embo NY Yankees/4.png",
    ],
    description_en:
      "The MLB BigBall Chunky Embo NY Yankees from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Giày thể thao hầm hố với kiểu dáng đế dày mạnh mẽ theo xu hướng hiện đại. Được chế tác từ chất liệu da tổng hợp cao cấp bền bỉ, dễ vệ sinh, nổi bật cùng logo New York Yankees thêu/in nổi sắc nét và lớp lót êm ái giúp giảm sốc tốt cả ngày dài.",
    sku: "RF-1010-MLB",
    material: "Da cao cấp",
  },
  {
    id: "P1011",
    name: "MLB Bigball Chunky Varsity La Dodgers Blue",
    brand: "MLB",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: null,
    colors: ["Cloud White", "Sky Blue"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.7,
    reviews: 261,
    isNew: false,
    onSale: false,
    stock: 45,
    gender: "Unisex",
    image: "assets/MLB Bigball Chunky Varsity La Dodgers Blue/1.png",
    gallery: [
      "assets/MLB Bigball Chunky Varsity La Dodgers Blue/1.png",
      "assets/MLB Bigball Chunky Varsity La Dodgers Blue/2.png",
      "assets/MLB Bigball Chunky Varsity La Dodgers Blue/3.png",
      "assets/MLB Bigball Chunky Varsity La Dodgers Blue/4.png",
    ],
    description_en:
      "The MLB Bigball Chunky Varsity La Dodgers Blue from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Blue.",
    description_vi:
      "Sở hữu thiết kế đế chunky dày giúp tôn dáng, giảm áp lực di chuyển và tăng chiều cao tự nhiên. Đôi giày làm từ vật liệu tổng hợp bền bỉ với tông xanh lam đặc trưng và logo in rõ nét đại diện cho đội bóng chày Los Angeles Dodgers.",
    sku: "RF-1011-MLB",
    material: "Da cao cấp",
  },
  {
    id: "P1012",
    name: "MLB Chunky Classic Dodgers 'White Navy'",
    brand: "MLB",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: 4125000,
    colors: ["Cloud White", "Sky Blue", "Navy"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.4,
    reviews: 284,
    isNew: true,
    onSale: true,
    stock: 48,
    gender: "Women",
    image: "assets/MLB Chunky Classic Dodgers 'White Navy'/1.png",
    gallery: [
      "assets/MLB Chunky Classic Dodgers 'White Navy'/1.png",
      "assets/MLB Chunky Classic Dodgers 'White Navy'/2.png",
      "assets/MLB Chunky Classic Dodgers 'White Navy'/3.png",
      "assets/MLB Chunky Classic Dodgers 'White Navy'/4.png",
    ],
    description_en:
      "The MLB Chunky Classic Dodgers 'White Navy' from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Navy.",
    description_vi:
      "Mẫu Court-shoe unisex mang phong cách streetwear năng động với chất liệu da tổng hợp phối vải lưới thoáng khí. Nổi bật nhờ sự tương phản giữa sắc trắng và xanh navy, họa tiết Monogram đặc trưng, logo Dodgers và đế cao su chống trượt chắc chắn.",
    sku: "RF-1012-MLB",
    material: "Da cao cấp",
  },
  {
    id: "P1013",
    name: "MLB Chunky Classic Varsity Boston Red Sox",
    brand: "MLB",
    category: "Lifestyle",
    price: 3590000,
    oldPrice: null,
    colors: ["Cloud White", "Crimson"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.1,
    reviews: 307,
    isNew: false,
    onSale: false,
    stock: 0,
    gender: "Men",
    image: "assets/MLB Chunky Classic Varsity Boston Red Sox/1.png",
    gallery: [
      "assets/MLB Chunky Classic Varsity Boston Red Sox/1.png",
      "assets/MLB Chunky Classic Varsity Boston Red Sox/2.png",
      "assets/MLB Chunky Classic Varsity Boston Red Sox/3.png",
      "assets/MLB Chunky Classic Varsity Boston Red Sox/4.png",
    ],
    description_en:
      "The MLB Chunky CLassic Varsity Boston Red Sox from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Red.",
    description_vi:
      "Giày Chunky phong cách Hàn Quốc làm bằng chất liệu da cao cấp có độ bền vượt trội. Thiết kế đế dày thời trang tạo cảm giác khỏe khoắn, ôm chân, đi kèm họa tiết logo Boston Red Sox in thêu nổi bật và lớp lót tối ưu độ êm ái khi di chuyển.",
    sku: "RF-1013-MLB",
    material: "Da cao cấp",
  },

  {
    id: "P1014",
    name: "MLB Chunky Wide Strike New York Yankees Black",
    brand: "MLB",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: null,
    colors: ["Jet Black", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.8,
    reviews: 330,
    isNew: false,
    onSale: false,
    stock: 4,
    gender: "Unisex",
    image: "assets/MLB Chunky Wide Strike New York Yankees Black/1.png",
    gallery: [
      "assets/MLB Chunky Wide Strike New York Yankees Black/1.png",
      "assets/MLB Chunky Wide Strike New York Yankees Black/2.png",
      "assets/MLB Chunky Wide Strike New York Yankees Black/3.png",
      "assets/MLB Chunky Wide Strike New York Yankees Black/4.png",
    ],
    description_en:
      "The MLB Chunky Wide Strike New York Yankees Black from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in Black.",
    description_vi:
      "Thiết kế với tông đen chủ đạo đầy cá tính, sang trọng và làm từ chất liệu tổng hợp thoáng khí, bền vững. Giày được trang bị phần đế chunky dày rộng giúp nâng tầm phong cách hack chiều cao và tạo điểm nhấn bằng logo New York Yankees tinh tế.",
    sku: "RF-1014-MLB",
    material: "Da cao cấp",
  },

  {
    id: "P1015",
    name: "MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy",
    brand: "MLB",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.5,
    reviews: 353,
    isNew: false,
    onSale: false,
    stock: 17,
    gender: "Women",
    image:
      "assets/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/1.png",
    gallery: [
      "assets/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/1.png",
      "assets/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/2.png",
      "assets/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/3.png",
      "assets/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/4.png",
    ],
    description_en:
      "The MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Sự kết hợp độc đáo giữa thể thao và thời trang khi sử dụng chất liệu vải denim (jeans) màu xanh navy cổ điển. Thân giày có form dáng chunky mạnh mẽ, in logo NY trắng tương phản rõ rệt cùng cấu trúc đế cao su dày dặn hỗ trợ tăng chiều cao đáng kể.",
    sku: "RF-1015-MLB",
    material: "Da cao cấp",
  },

  {
    id: "P1016",
    name: "New Balance 530 White Silver Green",
    brand: "New Balance",
    category: "Lifestyle",
    price: 2700000,
    oldPrice: 3375000,
    colors: ["Forest Green", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.2,
    reviews: 376,
    isNew: false,
    onSale: true,
    stock: 20,
    gender: "Men",
    image: "assets/New Balance 530 White Silver Green/1.png",
    gallery: [
      "assets/New Balance 530 White Silver Green/1.png",
      "assets/New Balance 530 White Silver Green/2.png",
      "assets/New Balance 530 White Silver Green/3.png",
      "assets/New Balance 530 White Silver Green/4.png",
    ],
    description_en:
      "The New Balance 530 White Silver Green from New Balance is crafted from leather and mesh fabric, built for everyday wear with a clean, versatile silhouette in Green/Silver.",
    description_vi:
      "Giày chạy bộ lấy cảm hứng từ thập niên 90 với thân bằng da tổng hợp và lưới thoáng khí. Phối màu trắng chủ đạo đan xen các chi tiết xanh lá nhạt và bạc ở logo \"N\", đi cùng đế giữa midsole nhẹ, đàn hồi giảm chấn mang lại trải nghiệm vintage êm ái.",
    sku: "RF-1016-NEW",
    material: "Da và vải lưới",
  },
  {
    id: "P1017",
    name: "New Balance 550 'White Mint Green'",
    brand: "New Balance",
    category: "Lifestyle",
    price: 3000000,
    oldPrice: null,
    colors: ["Cloud White", "Sky Blue"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.9,
    reviews: 399,
    isNew: false,
    onSale: false,
    stock: 23,
    gender: "Unisex",
    image: "assets/New Balance 550 'White Mint Green'/1.png",
    gallery: [
      "assets/New Balance 550 'White Mint Green'/1.png",
      "assets/New Balance 550 'White Mint Green'/2.png",
      "assets/New Balance 550 'White Mint Green'/3.png",
      "assets/New Balance 550 'White Mint Green'/4.png",
    ],
    description_en:
      "The New Balance 550 'White Mint Green' from New Balance is crafted from premium animal leather, built for everyday wear with a clean, versatile silhouette in White/Green.",
    description_vi:
      "Biểu tượng thời trang tươi mới mang sự kết hợp hoàn hảo giữa chất liệu da và vải cao cấp. Phom dáng Court-shoe đơn giản, hiện đại mang sắc trắng chủ đạo phối cùng màu xanh mint trẻ trung và các logo định vị thương hiệu tinh tế quanh thân giày.",
    sku: "RF-1017-NEW",
    material: "Da thú",
  },

  {
    id: "P1018",
    name: "Air Jordan 1 Low 'Grey White'",
    brand: "Nike",
    category: "Basketball",
    price: 3000000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.6,
    reviews: 422,
    isNew: true,
    onSale: false,
    stock: 26,
    gender: "Women",
    image: "assets/Air Jordan 1 Low 'Grey White'/1.png",
    gallery: [
      "assets/Air Jordan 1 Low 'Grey White'/1.png",
      "assets/Air Jordan 1 Low 'Grey White'/2.png",
      "assets/Air Jordan 1 Low 'Grey White'/3.png",
      "assets/Air Jordan 1 Low 'Grey White'/4.png",
    ],
    description_en:
      "The Air Jordan 1 Low 'Grey White' from Nike is crafted from leather, built for everyday wear with a clean, versatile silhouette in Grey White.",
    description_vi:
      "Dòng giày huyền thoại mang phối màu trung tính hiện đại kết hợp giữa hai tông xám nhạt và trắng thanh lịch. Thân giày bằng da cao cấp ôm chân, nổi bật với logo Swoosh và biểu tượng Wings ở gót, đi kèm đế đệm Air nhẹ êm chống trượt.",
    sku: "RF-1018-NIK",
    material: "Da",
  },

  {
    id: "P1019",
    name: "Nike Air Force 1 White",
    brand: "Nike",
    category: "Lifestyle",
    price: 2500000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.3,
    reviews: 445,
    isNew: false,
    onSale: false,
    stock: 29,
    gender: "Men",
    image: "assets/Nike Air Force 1 White/1.png",
    gallery: [
      "assets/Nike Air Force 1 White/1.png",
      "assets/Nike Air Force 1 White/2.png",
      "assets/Nike Air Force 1 White/3.png",
      "assets/Nike Air Force 1 White/4.png",
    ],
    description_en:
      "The Nike Air Force 1 White from Nike is crafted from smooth leather material, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Biểu tượng thời trang đường phố thế giới sở hữu thiết kế tối giản vượt thời gian. Giày được làm bằng chất liệu da trơn màu trắng tinh khiết, tạo điểm nhấn bằng logo Swoosh cùng đế giữa tích hợp đệm bọt khí Nike Air mang lại sự êm ái tối đa.",
    sku: "RF-1019-NIK",
    material: "Chất liệu da trơn",
  },

  {
    id: "P1020",
    name: "Nike Air Max 1 Premium 'Black and Playful Pink'",
    brand: "Nike",
    category: "Running",
    price: 4290000,
    oldPrice: 5362000,
    colors: ["Jet Black", "Pink"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.0,
    reviews: 468,
    isNew: false,
    onSale: true,
    stock: 32,
    gender: "Unisex",
    image: "assets/Nike Air Max 1 Premium 'Black and Playful Pink'/1.png",
    gallery: [
      "assets/Nike Air Max 1 Premium 'Black and Playful Pink'/1.png",
      "assets/Nike Air Max 1 Premium 'Black and Playful Pink'/2.png",
      "assets/Nike Air Max 1 Premium 'Black and Playful Pink'/3.png",
      "assets/Nike Air Max 1 Premium 'Black and Playful Pink'/4.png",
    ],
    description_en:
      "The Nike Air Max 1 Premium 'Black and Playful Pink' from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in Black/Playful Pink.",
    description_vi:
      "Phiên bản Premium làm từ da cao cấp phối vải lưới, tạo tương phản mạnh mẽ giữa sắc đen cổ điển và hồng tươi phá cách. Giày ứng dụng công nghệ đế khí Air Max lộ ngoài đặc trưng kết hợp đệm EVA nhẹ, tối ưu khả năng giảm chấn và bám đường.",
    sku: "RF-1020-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1021",
    name: "Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'",
    brand: "Nike",
    category: "Basketball",
    price: 2990000,
    oldPrice: null,
    colors: ["Cloud White", "Forest Green", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.7,
    reviews: 11,
    isNew: false,
    onSale: false,
    stock: 4,
    gender: "Women",
    image:
      "assets/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/1.png",
    gallery: [
      "assets/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/1.png",
      "assets/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/2.png",
      "assets/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/3.png",
      "assets/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/4.png",
    ],
    description_en:
      "The Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey' from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Light Smoke Grey-Electric Green.",
    description_vi:
      "Thiết kế bóng rổ cổ điển hướng tới sự bền vững với thân da trắng làm từ vật liệu tái chế. Điểm nhấn nằm ở dấu Swoosh bằng nỉ tái chế 100%, lưỡi gà xốp lộ ra ngoài cá tính cùng lót giày màu Volt và đế ngoài cao su Nike Grind thân thiện với môi trường.",
    sku: "RF-1021-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1022",
    name: "Nike Dunk Low 'Panda' 2025",
    brand: "Nike",
    category: "Lifestyle",
    price: 2900000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.4,
    reviews: 34,
    isNew: false,
    onSale: false,
    stock: 38,
    gender: "Men",
    image: "assets/Nike Dunk Low 'Panda' 2025/1.png",
    gallery: [
      "assets/Nike Dunk Low 'Panda' 2025/1.png",
      "assets/Nike Dunk Low 'Panda' 2025/2.png",
      "assets/Nike Dunk Low 'Panda' 2025/3.png",
      "assets/Nike Dunk Low 'Panda' 2025/4.png",
    ],
    description_en:
      "The Nike Dunk Low 'Panda' 2025 from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Phom dáng cổ thấp năng động làm từ da cao cấp phối mảng da lộn tạo chiều sâu cấu trúc. Phối màu đen-trắng 'Panda' tương phản kinh điển cực kỳ dễ phối đồ, đi kèm logo Swoosh đen nổi bật và đế ngoài cao su có rãnh vân tăng độ ổn định.",
    sku: "RF-1022-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1023",
    name: "Nike Invincible 3 'Pink Foam'",
    brand: "Nike",
    category: "Running",
    price: 6300000,
    oldPrice: null,
    colors: ["Pink", "Slate Grey"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.1,
    reviews: 57,
    isNew: false,
    onSale: false,
    stock: 41,
    gender: "Unisex",
    image: "assets/Nike Invincible 3 'Pink Foam'/1.png",
    gallery: [
      "assets/Nike Invincible 3 'Pink Foam'/1.png",
      "assets/Nike Invincible 3 'Pink Foam'/2.png",
      "assets/Nike Invincible 3 'Pink Foam'/3.png",
      "assets/Nike Invincible 3 'Pink Foam'/4.png",
    ],
    description_en:
      "The Nike Invincible 3 'Pink Foam' from Nike is crafted from Flyknit fabric, built for everyday wear with a clean, versatile silhouette in Pink.",
    description_vi:
      "Giày chạy bộ đường dài chuyên dụng dệt từ sợi Flyknit siêu nhẹ và thoáng khí. Phom dáng hiện đại mang gam màu Pink Foam nổi bật, trang bị hệ thống cáp Flywire giữ chân chắc chắn cùng bộ đệm ZoomX dày ở gót mang đến khả năng phản hồi lực cực cao.",
    sku: "RF-1023-NIK",
    material: "Vải Flyknit",
  },

  {
    id: "P1024",
    name: "Nike SB Dunk Low Pro Be True",
    brand: "Nike",
    category: "Lifestyle",
    price: 6300000,
    oldPrice: 7875000,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.8,
    reviews: 80,
    isNew: true,
    onSale: true,
    stock: 44,
    gender: "Women",
    image: "assets/Nike SB Dunk Low Pro Be True/1.png",
    gallery: [
      "assets/Nike SB Dunk Low Pro Be True/1.png",
      "assets/Nike SB Dunk Low Pro Be True/2.png",
      "assets/Nike SB Dunk Low Pro Be True/3.png",
      "assets/Nike SB Dunk Low Pro Be True/4.png",
    ],
    description_en:
      "The Nike SB Dunk Low Pro Be True from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Thiết kế ra mắt năm 2022 thuộc dòng Nike SB mang chất liệu da cao cấp mềm mại. Thân giày phối sắc đen chủ đạo kết hợp các chi tiết trắng và xanh dương sặc sỡ độc đáo, tích hợp đệm khí Nike Air ở đế và các lỗ thông hơi giúp tối ưu sự thoải mái.",
    sku: "RF-1024-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1025",
    name: "Nike Zoom Vomero 5 'Yankees'",
    brand: "Nike",
    category: "Running",
    price: 4200000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.5,
    reviews: 103,
    isNew: false,
    onSale: false,
    stock: 47,
    gender: "Men",
    image: "assets/Nike Zoom Vomero 5 'Yankees'/1.png",
    gallery: [
      "assets/Nike Zoom Vomero 5 'Yankees'/1.png",
      "assets/Nike Zoom Vomero 5 'Yankees'/2.png",
      "assets/Nike Zoom Vomero 5 'Yankees'/3.png",
      "assets/Nike Zoom Vomero 5 'Yankees'/4.png",
    ],
    description_en:
      "The Nike Zoom Vomero 5 'Yankees' from Nike is crafted from mesh and synthetic leather, built for everyday wear with a clean, versatile silhouette in Silver/White.",
    description_vi:
      "Giày thể thao cổ điển lấy cảm hứng từ đội bóng Yankees với sắc xanh navy phối trắng và bạc. Phần upper kết hợp vải lưới mesh và da tổng hợp thoáng khí, trang bị công nghệ đệm Zoom Air giảm sốc tối đa ở đế giữa và logo thêu tỉ mỉ ở gót.",
    sku: "RF-1025-NIK",
    material: "Lưới và Da tổng hợp",
  },

  {
    id: "P1026",
    name: "PUMA Roma 68 Revival 'Black Gold'",
    brand: "PUMA",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White", "Gold"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.2,
    reviews: 126,
    isNew: false,
    onSale: false,
    stock: 0,
    gender: "Unisex",
    image: "assets/PUMA Roma 68 Revival 'Black Gold'/1.png",
    gallery: [
      "assets/PUMA Roma 68 Revival 'Black Gold'/1.png",
      "assets/PUMA Roma 68 Revival 'Black Gold'/2.png",
      "assets/PUMA Roma 68 Revival 'Black Gold'/3.png",
      "assets/PUMA Roma 68 Revival 'Black Gold'/4.png",
    ],
    description_en:
      "The PUMA Roma 68 Revival 'Black Gold' from PUMA is crafted from premium leather combining both suede and smooth leather finishes, built for everyday wear with a clean, versatile silhouette in Black/White/Gold.",
    description_vi:
      "Thiết kế lấy cảm hứng từ dòng Palermo cổ điển với phần thân bằng da lộn cao cấp kết hợp da trơn mềm mại. Phối màu đen-trắng truyền thống được nâng tầm bằng các chi tiết logo mạ vàng kim sang trọng cùng hệ thống dây giày bản rộng (Wide Lace) phá cách.",
    sku: "RF-1026-PUM",
    material: "Da cao cấp được kết hợp giữa da lộn và da trơn",
  },

  {
    id: "P1027",
    name: "Puma Speedcat OG 'Dark Brown'",
    brand: "PUMA",
    category: "Lifestyle",
    price: 4400000,
    oldPrice: null,
    colors: ["Brown", "Slate Grey"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.9,
    reviews: 149,
    isNew: false,
    onSale: false,
    stock: 13,
    gender: "Women",
    image: "assets/Puma Speedcat OG 'Dark Brown'/1.png",
    gallery: [
      "assets/Puma Speedcat OG 'Dark Brown'/1.png",
      "assets/Puma Speedcat OG 'Dark Brown'/2.png",
      "assets/Puma Speedcat OG 'Dark Brown'/3.png",
      "assets/Puma Speedcat OG 'Dark Brown'/4.png",
    ],
    description_en:
      "The Puma Speedcat OG 'Dark Brown' from PUMA is crafted from synthetic leather and mesh fabric, built for everyday wear with a clean, versatile silhouette in Dark Brown.",
    description_vi:
      "Mẫu giày mang đậm phong cách retro, tối giản đầy mạnh mẽ với tông màu nâu đậm cổ điển. Thân giày chế tác từ da tổng hợp cao cấp đan xen vải lưới giúp giảm nhiệt, đi kèm phom dáng low-top ôm sát chân linh hoạt và hệ thống dây buộc truyền thống.",
    sku: "RF-1027-PUM",
    material: "Da tổng hợp và vải lưới",
  },

  {
    id: "P1028",
    name: "Vans Old Skool OG LX Black White",
    brand: "Vans",
    category: "Lifestyle",
    price: 2900000,
    oldPrice: 3625000,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.6,
    reviews: 172,
    isNew: false,
    onSale: true,
    stock: 4,
    gender: "Men",
    image: "assets/Vans Old Skool OG LX Black White/1.png",
    gallery: [
      "assets/Vans Old Skool OG LX Black White/1.png",
      "assets/Vans Old Skool OG LX Black White/2.png",
      "assets/Vans Old Skool OG LX Black White/3.png",
      "assets/Vans Old Skool OG LX Black White/4.png",
    ],
    description_en:
      "The Vans Old Skool OG LX Black White from Vans is crafted from suede and canvas fabric, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Phiên bản nâng cấp thời thượng của dòng Old Skool cổ điển với upper làm từ da lộn phối vải canvas dày dặn, thoáng khí. Phối màu Đen-Trắng tối giản kết hợp với đường may tinh xảo, logo gót chân và đế ngoài cao su lưu hóa họa tiết waffle bám đường.",
    sku: "RF-1028-VAN",
    material: "Da lộn và vải canvas",
  },

  {
    id: "P1029",
    name: "Vans Style 36 Decon SF",
    brand: "Vans",
    category: "Lifestyle",
    price: 2900000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.3,
    reviews: 195,
    isNew: false,
    onSale: false,
    stock: 19,
    gender: "Unisex",
    image: "assets/Vans Style 36 Decon SF/1.png",
    gallery: [
      "assets/Vans Style 36 Decon SF/1.png",
      "assets/Vans Style 36 Decon SF/2.png",
      "assets/Vans Style 36 Decon SF/3.png",
      "assets/Vans Style 36 Decon SF/4.png",
    ],
    description_en:
      "The Vans Style 36 Decon SF from Vans is crafted from premium fabric, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Thiết kế Court-shoe cổ điển mang kiểu dáng low-top gọn gàng, năng động với vải cao cấp dẻo dai. Sự kết hợp tương phản giữa thân giày đen và đế cao su trắng truyền thống có vân sóng đặc trưng, dễ dàng mix-match với mọi trang phục streetwear.",
    sku: "RF-1029-VAN",
    material: "Vải cao cấp",
  },
];

function rfFormatVND(n) {
  return n.toLocaleString("vi-VN") + "đ";
}

function rfGetProduct(id) {
  return RF_PRODUCTS.find((p) => p.id === id);
}
