/*==========================================================================
   RAPIDFEET — Product Catalog
==========================================================================*/

const RF_BRANDS = [
  "Adidas",
  "Nike",
  "PUMA",
  "Vans",
  "Converse",
  "New Balance",
  "MLB",
];

const RF_COLORS = {
  "Jet Black": "#0D0D0D",
  "Cloud White": "#FAFAF8",
  "Ember Orange": "#FF5A1F",
  "Volt Purple": "#6B4EFF",
  "Slate Grey": "#6E6E6E",
  "Forest Green": "#2C5F3F",
  Sand: "#D8C7A8",
  Crimson: "#B3261E",
  Navy: "#1B2A4A",
  "Sky Blue": "#7EC8E3",
  Gold: "#D4AF37",
  Pink: "#F2A6C1",
  Brown: "#5C4332",
};

const RF_CATEGORIES = ["Running", "Lifestyle", "Basketball"];

function rfImg(seed, w = 600, h = 600) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

const RF_PRODUCTS = [
  {
    id: "P1000",
    name: "Adidas Forum Low CL 'Off White'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: 3250000,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.0,
    reviews: 8,
    isNew: false,
    onSale: true,
    stock: 0,
    gender: "Women",
    image: "../../img/Adidas Forum Low CL ‘Off White’/1.jpg",
    gallery: [
      "../../img/Adidas Forum Low CL ‘Off White’/1.jpg",
      "../../img/Adidas Forum Low CL ‘Off White’/2.jpg",
      "../../img/Adidas Forum Low CL ‘Off White’/3.jpg",
      "../../img/Adidas Forum Low CL ‘Off White’/4.jpg",
    ],
    description_en:
      "The Adidas Forum Low CL 'Off White' from Adidas is crafted from premium synthetic leather, built for everyday wear with a clean, versatile silhouette in Off White.",
    description_vi:
      "Trong thế giới giày sneaker, Adidas Forum Low luôn là một biểu tượng vượt thời gian, đại diện cho sự kết hợp hoàn hảo giữa di sản thể thao và thời trang đường phố. Ở phiên bản Forum Low CL ‘Off White’ , đôi giày được khoác lên mình diện mạo mới – nhẹ nhàng, thanh lịch nhưng vẫn giữ trọn vẹn tinh thần của dòng Forum huyền thoại.\n1.Thiết kế\nSắc Off White (trắng ngà) mang lại vẻ ngoài trang nhã, tinh giản, khác biệt so với những đôi giày trắng tinh thông thường. Đây là tông màu lý tưởng cho những ai yêu thích sự tối giản nhưng vẫn muốn tạo điểm nhấn tinh tế trong từng chi tiết. Thiết kế này không chỉ dễ phối đồ mà còn mang lại cảm giác sạch sẽ, cao cấp và không bao giờ lỗi mốt.\n2.Chất liệu\nPhần upper được làm từ chất liệu da tổng hợp cao cấp, kết hợp cùng các đường khâu nổi bật, tạo nên cấu trúc chắc chắn và cảm giác ôm chân thoải mái. Chi tiết quai dán đặc trưng của dòng Forum vẫn được giữ lại – như một lời nhắc về quá khứ huy hoàng trên sân bóng rổ, đồng thời tạo điểm nhấn thẩm mỹ cá tính. Phần đế cao su bền bỉ cùng lớp đệm êm ái bên trong giúp người dùng tự tin di chuyển cả ngày dài.",
    sku: "RF-1000-ADI",
    material: "Da tổng hợp cao cấp",
  },

  {
    id: "P1001",
    name: "Adidas originals Stan Smith 'Cloud White Gold'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.7,
    reviews: 31,
    isNew: false,
    onSale: false,
    stock: 15,
    gender: "Men",
    image: "../../img/Adidas originals Stan Smith ‘Cloud White Gold’/1.jpg",
    gallery: [
      "../../img/Adidas originals Stan Smith ‘Cloud White Gold’/1.jpg",
      "../../img/Adidas originals Stan Smith ‘Cloud White Gold’/2.avif",
      "../../img/Adidas originals Stan Smith ‘Cloud White Gold’/3.avif",
      "../../img/Adidas originals Stan Smith ‘Cloud White Gold’/4.avif",
    ],
    description_en:
      "The Adidas originals Stan Smith 'Cloud White Gold' from Adidas is crafted from genuine leather, built for everyday wear with a clean, versatile silhouette in Cloud White.",
    description_vi:
      "Giày adidas Originals Stan Smith ‘Cloud White Gold’ là phiên bản đặc biệt của mẫu giày Stan Smith nổi tiếng, với thiết kế cổ điển nhưng lại mang những điểm nhấn tinh tế và sang trọng, đặc biệt là phần chi tiết màu vàng gold, làm nổi bật thương hiệu và tạo vẻ ngoài cao cấp cho đôi giày.\n1.Thiết kế\nMàu sắc: Đôi giày có màu Cloud White (màu trắng tinh khiết), mang đến vẻ ngoài thanh thoát và dễ dàng phối hợp với nhiều loại trang phục khác nhau. Các chi tiết nhỏ như phần logo và các đường chỉ may màu vàng Gold tạo điểm nhấn sang trọng và hiện đại cho thiết kế cổ điển của đôi giày.\n2.Chất liệu\n-Thiết kế phần thân: Phần trên của giày được làm từ da thật cao cấp, mang lại vẻ ngoài sang trọng và độ bền cao. Da thật không chỉ có khả năng giữ form tốt mà còn mang lại sự thoải mái và độ bền lâu dài cho đôi giày.\n-Đế giày: Đế giày được làm từ cao su chất lượng, với thiết kế đơn giản nhưng hiệu quả, mang lại sự bám tốt trên nhiều loại bề mặt khác nhau. Đế giày mềm mại và linh hoạt, giúp bạn di chuyển thoải mái cả ngày dài.\n-Logo và chi tiết đặc trưng: Một trong những điểm nổi bật của phiên bản ‘Cloud White Gold’ chính là chi tiết logo vàng gold trên lưỡi giày và phần gót giày. Logo Stan Smith đặc trưng được thêu với đường viền vàng gold sang trọng, tạo nên sự nổi bật cho mẫu giày. Ngoài ra, tên của Stan Smith cũng được in trên lưỡi giày, giữ lại những nét đặc trưng của dòng giày huyền thoại này.\n3.Đặc điểm nổi bật\n-Phong cách cổ điển với điểm nhấn sang trọng: Màu trắng tinh khiết kết hợp với các chi tiết vàng gold tạo nên một đôi giày vừa cổ điển vừa hiện đại, dễ dàng phối hợp với nhiều trang phục khác nhau từ đồ thể thao đến trang phục casual.\n-Logo Stan Smith đặc trưng: Logo Stan Smith với đường viền vàng gold giúp giày trở nên nổi bật và dễ dàng nhận diện thương hiệu.",
    sku: "RF-1001-ADI",
    material: "Da thật",
  },

  {
    id: "P1002",
    name: "Adidas Samba JP 'Collegiate Green'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 3000000,
    oldPrice: null,
    colors: ["Forest Green", "Slate Grey"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.4,
    reviews: 54,
    isNew: false,
    onSale: false,
    stock: 18,
    gender: "Unisex",
    image: "../../img/Adidas Samba JP ‘Collegiate Green’/1.jpg",
    gallery: [
      "../../img/Adidas Samba JP ‘Collegiate Green’/1.jpg",
      "../../img/Adidas Samba JP ‘Collegiate Green’/2.png",
      "../../img/Adidas Samba JP ‘Collegiate Green’/3.png",
    ],
    description_en:
      "The Adidas Samba JP 'Collegiate Green' from Adidas is crafted from suede, built for everyday wear with a clean, versatile silhouette in White/Green.",
    description_vi:
      "Adidas Samba – một biểu tượng trường tồn của làng sneaker – luôn biết cách làm mới mình mà không đánh mất tinh thần nguyên bản. Trong số những phiên bản nổi bật gần đây, Adidas Samba JP ‘Collegiate Green’  gây ấn tượng mạnh mẽ nhờ sự kết hợp độc đáo giữa phong cách retro châu Âu và tinh thần thẩm mỹ tinh tế của Nhật Bản.\n1.Thiết kế\nNgay từ ánh nhìn đầu tiên, đôi giày này đã thu hút bởi tông xanh lá đậm (collegiate green) mạnh mẽ, cá tính nhưng vẫn mang dáng vẻ cổ điển đầy cuốn hút. Màu xanh không chỉ khiến đôi giày nổi bật giữa đám đông mà còn dễ dàng phối với nhiều phong cách thời trang khác nhau – từ vintage, casual cho đến streetwear hiện đại.\n2.Chất liệu\n-Phần upper của giày được chế tác từ da lộn mềm mịn, kết hợp với những đường nét da trơn ở logo 3 sọc đặc trưng, tạo nên cảm giác sang trọng và tinh xảo. Logo “Samba” màu vàng ánh kim bên hông giày là chi tiết nhỏ nhưng đầy sức hút, làm nổi bật yếu tố thương hiệu và tăng thêm chiều sâu cho tổng thể thiết kế.\n-Phần đế cao su màu gum cổ điển – một đặc trưng không thể thiếu của dòng Samba – không chỉ đem lại cảm giác bám tốt, êm ái khi di chuyển mà còn tăng thêm tính hoài cổ cho thiết kế. Dáng low-top đặc trưng, ôm gọn bàn chân, dễ dàng phối cùng quần jeans, quần tây ống đứng hay cả quần short thể thao.\n3.Phong cách thiết kế\nĐặc biệt, phiên bản Samba JP (Japan Pack) này mang theo hơi hướng thẩm mỹ tối giản và tinh tế của Nhật Bản. Từng đường cắt, đường chỉ đều được chăm chút tỉ mỉ, gọn gàng – đúng với tinh thần “ít nhưng chất” của người Nhật. Phần lót giày, hộp giày và các chi tiết phụ cũng được hoàn thiện với chất lượng cao, khiến đôi giày không chỉ đẹp ở vẻ ngoài mà còn đáng giá ở sự chỉn chu bên trong.",
    sku: "RF-1002-ADI",
    material: "Da lộn",
  },
  {
    id: "P1003",
    name: "Adidas Samba OG 'Cloud White Light Blue'",
    brand: "Adidas",
    category: "Running",
    price: 3290000,
    oldPrice: null,
    colors: ["Cloud White", "Sky Blue"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.1,
    reviews: 77,
    isNew: false,
    onSale: false,
    stock: 21,
    gender: "Women",
    image: "../../img/Adidas Samba OG ‘Cloud White Light Blue’/1.jpg",
    gallery: [
      "../../img/Adidas Samba OG ‘Cloud White Light Blue’/1.jpg",
      "../../img/Adidas Samba OG ‘Cloud White Light Blue’/2.avif",
      "../../img/Adidas Samba OG ‘Cloud White Light Blue’/3.avif",
      "../../img/Adidas Samba OG ‘Cloud White Light Blue’/4.jpg",
    ],
    description_en:
      "The Adidas Samba OG 'Cloud White Light Blue' from Adidas is crafted from leather, mesh, and suede, built for everyday wear with a clean, versatile silhouette in Cloud White/Light Blue.",
    description_vi:
      "Giày adidas Samba OG ‘Cloud White Light Blue’  là một phiên bản của mẫu Samba OG nổi tiếng, với thiết kế cổ điển và màu sắc hiện đại. Đây là một đôi giày thể thao mang phong cách retro với các chi tiết đặc trưng của adidas. Dưới đây là mô tả chi tiết về sản phẩm:\n1. Thiết kế chung \n-Màu sắc: Giày chủ yếu có màu Cloud White (trắng nhạt) với các chi tiết màu Light Blue (xanh nhạt). Màu Cloud White tạo nền tảng sạch sẽ và dễ phối hợp, trong khi màu Light Blue mang đến điểm nhấn nhẹ nhàng và tươi mới.\n-Phong cách: adidas Samba OG ‘Cloud White Light Blue’ mang phong cách cổ điển của dòng Samba, nổi bật with thiết kế retro and màu sắc hiện đại. Đây là mẫu giày thể thao phù hợp cho cả hoạt động thể thao nhẹ và phong cách hàng ngày.\n2. Chất liệu\n-Phần trên (Upper):\n    -Chất liệu:Da: Phần trên của giày được làm từ da cao cấp, cung cấp độ bền và cảm giác sang trọng. Da có màu Cloud White, tạo nên vẻ ngoài sạch sẽ và tinh tế.\n    -Vải lưới: Có thể có các chi tiết bằng vải lưới để cải thiện độ thông thoáng và nhẹ nhàng.\n    -Da lộn: Các chi tiết màu Light Blue thường được làm từ da lộn hoặc chất liệu tương tự, tạo thêm sự phong cách và khác biệt cho giày.\n-Chi tiết: Giày có thiết kế cổ điển với các chi tiết nổi bật như ba sọc adidas trên hai bên, biểu tượng Trefoil trên lưỡi gà, và các đường chỉ may tinh tế. Các chi tiết màu Light Blue thường xuất hiện ở các lớp da hoặc da lộn trên nền trắng, tạo ra một sự tương phản nổi bật.\n-Hệ thống đế:\n    -Đệm: Giày sử dụng công nghệ đệm truyền thống của adidas, với lớp đệm nhẹ giúp cung cấp sự êm ái và hỗ trợ khi di chuyển. Mặc dù không có công nghệ đệm đặc biệt, nhưng đệm vẫn mang lại sự thoải mái cơ bản.\n-Đế ngoài: Đế ngoài bằng cao su với thiết kế các họa tiết chống trơn trượt, giúp tăng cường độ bám và độ bền trên nhiều bề mặt khác nhau. Đế ngoài có thiết kế retro đặc trưng của dòng Samba, với các họa tiết rãnh sâu để tạo độ bám tốt hơn.\nPhần lót trong (Insole) và cổ chân:\n-Lót trong: Lót trong của giày được thiết kế để cung cấp sự thoải mái và hỗ trợ chân tốt. Chất liệu lót trong có khả năng hút ẩm, giúp giữ cho chân luôn khô ráo và thoải mái.\n-Cổ chân: Phần cổ chân có lớp đệm nhẹ, tạo cảm giác vừa vặn và êm ái. Lớp đệm này hỗ trợ tốt cho vùng mắt cá chân và giảm căng thẳng khi di chuyển.\nHệ thống buộc dây:\n    Dây giày: Dây giày chắc chắn và dễ điều chỉnh, giúp giày vừa vặn và ổn định. Dây giày cũng giúp việc mang và tháo giày trở nên dễ dàng hơn.\n3.Tính năng đặc biệt:\n-Thiết kế cổ điển với màu sắc hiện đại: Màu Cloud White và Light Blue tạo ra một vẻ ngoài cổ điển nhưng tươi mới, dễ dàng phối hợp với nhiều loại trang phục.\n-Chất liệu cao cấp và thiết kế retro: Sự kết hợp giữa da cao cấp và các chi tiết thiết kế retro của dòng Samba làm cho giày không chỉ bền bỉ mà còn rất phong cách.\nadidas Samba OG ‘Cloud White Light Blue’ JI2003 là một đôi giày thể thao lý tưởng cho những ai yêu thích sự kết hợp giữa phong cách cổ điển và màu sắc hiện đại. Với thiết kế tinh tế và chất lượng cao, giày này phù hợp cho cả hoạt động thể thao nhẹ và phong cách hàng ngày.",
    sku: "RF-1003-ADI",
    material: "Da/Vải lưới/Da lộn",
  },

  {
    id: "P1004",
    name: "Adidas Superstar II 'Cloud White'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: 3250000,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.8,
    reviews: 100,
    isNew: false,
    onSale: true,
    stock: 24,
    gender: "Men",
    image: "../../img/Adidas Superstar II 'Cloud White'/1.jpg",
    gallery: [
      "../../img/Adidas Superstar II 'Cloud White'/1.jpg",
      "../../img/Adidas Superstar II 'Cloud White'/2.jpg",
      "../../img/Adidas Superstar II 'Cloud White'/3.jpg",
      "../../img/Adidas Superstar II 'Cloud White'/4.jpg",
    ],
    description_en:
      "The Adidas Superstar II 'Cloud White' from Adidas is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Black.",
    description_vi:
      "Giày Adidas Superstar II Cloud White JI0124 là phiên bản nâng cấp của mẫu giày huyền thoại Adidas Superstar, nổi bật với thiết kế cổ điển nhưng vẫn rất thời thượng và phù hợp với phong cách hiện đại. Màu sắc Cloud White (Trắng Mây) tạo nên một vẻ ngoài sạch sẽ, tinh tế và dễ dàng phối hợp với nhiều trang phục khác nhau. Đây là một đôi giày lý tưởng cho những ai yêu thích sự kết hợp giữa phong cách cổ điển và tính ứng dụng cao trong cuộc sống hàng ngày. Dưới đây là mô tả chi tiết về đôi giày này:\n1.Thiết kế\nGiày Adidas Superstar II Cloud White có màu chủ đạo là Cloud White, một màu trắng tinh khiết tạo cảm giác nhẹ nhàng và dễ phối đồ. Màu trắng này cũng giúp giày trở nên dễ dàng kết hợp với nhiều loại trang phục, từ quần jean, quần thể thao đến các bộ đồ casual khác. Thiết kế vẫn giữ nguyên hình dáng biểu tượng của dòng Superstar, với mũi giày hình vỏ sò đặc trưng, tạo nên phong cách dễ nhận diện.\n2.Chất liệu\n-Upper (Phần trên giày): Giày được làm từ da tổng hợp cao cấp, giúp giày có độ bền cao và dễ dàng vệ sinh. Da tổng hợp này cũng giúp giày giữ được độ mềm mại và thoải mái khi mang, đồng thời tạo nên sự sang trọng và thời trang cho sản phẩm.\n-Đế giày: Đế giày được làm từ cao su bền bỉ, với họa tiết đường vân đặc trưng giúp tăng độ bám và giảm trơn trượt. Đế giày thiết kế đơn giản nhưng rất hiệu quả trong việc hỗ trợ người mang di chuyển ổn định trên các bề mặt khác nhau.\n-Mũi giày: Đặc trưng của dòng Adidas Superstar, mũi giày hình vỏ sò bằng cao su giúp bảo vệ ngón chân và tạo điểm nhấn đặc biệt cho thiết kế.\n3. Logo và biểu tượng\nGiày Adidas Superstar II Cloud White JI0124 vẫn giữ những chi tiết biểu tượng của dòng Superstar, bao gồm ba sọc Adidas nổi bật ở hai bên hông giày, cùng với logo Adidas Trefoil trên lưỡi gà. Những chi tiết này giúp tạo nên vẻ ngoài đặc trưng và dễ nhận diện của dòng giày Superstar, gắn liền với lịch sử phát triển của Adidas.\n3. Phong cách và ứng dụng\nGiày Adidas Superstar II Cloud White JI0124 không chỉ là đôi giày thể thao, mà còn là món đồ thời trang đường phố được yêu thích trên toàn thế giới. Với màu sắc trắng tinh tế và thiết kế cổ điển, đôi giày này rất dễ dàng kết hợp với nhiều loại trang phục khác nhau, từ quần jeans, quần short cho đến các bộ đồ thể thao hoặc casual. Đây là đôi giày lý tưởng cho những ai yêu thích sự đơn giản nhưng vẫn muốn nổi bật với phong cách thể thao cổ điển.",
    sku: "RF-1004-ADI",
    material: "Da cao cấp",
  },

  {
    id: "P1005",
    name: "Adidas Yeezy Boost 380 'Azure Non-Reflective'",
    brand: "Adidas",
    category: "Lifestyle",
    price: 7900000,
    oldPrice: null,
    colors: ["Sky Blue", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.5,
    reviews: 123,
    isNew: false,
    onSale: false,
    stock: 27,
    gender: "Unisex",
    image: "../../img/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/1.png",
    gallery: [
      "../../img/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/1.png",
      "../../img/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/2.png",
      "../../img/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/3.png",
      "../../img/Adidas Yeezy Boost 380 ‘Azure Non-Reflective’/4.png",
    ],
    description_en:
      "The Adidas Yeezy Boost 380 'Azure Non-Reflective' from Adidas is crafted from Primeknit, built for everyday wear with a clean, versatile silhouette in Light Blue.",
    description_vi:
      "Adidas Yeezy Boost 380 ‘Azure Non-Reflective’ là một lựa chọn tuyệt vời cho những ai yêu thích phong cách thời trang, trẻ trung, năng động và tìm kiếm một đôi giày thoải mái, êm ái khi mang. Đặc biệt phù hợp với những ai không thích chi tiết phản quang. Đôi giày này phù hợp với nhiều hoạt động hàng ngày, từ đi dạo phố, du lịch đến chơi thể thao nhẹ.\n\n1.Thiết kế:\n\nKiểu dáng cổ thấp ôm chân, linh hoạt và dễ phối đồ với nhiều phong cách khác nhau.\nThân giày được làm từ chất liệu Primeknit dệt kim liền mạch, mang lại cảm giác thoải mái và thoáng khí khi mang.\nMàu xanh lam nhạt chủ đạo, gợi liên tưởng đến bầu trời mùa hè, tạo nên vẻ ngoài trẻ trung, năng động và thu hút.\nSọc đơn màu cam nổi bật dọc thân giày, tạo điểm nhấn bắt mắt và cá tính.\nDây giày màu be hài hòa với tổng thể, mang đến sự tinh tế.\nKhông có chi tiết phản quang, trái ngược với phiên bản “Azure Reflective” cùng tên.\n2.Công nghệ:\n\nĐế giữa Boost màu trắng nổi bật, sử dụng công nghệ Boost tiên tiến của adidas, giúp hấp thụ lực va chạm hiệu quả và mang lại cảm giác êm ái, đàn hồi cao khi di chuyển.\nĐế ngoài bằng cao su bền bỉ, chống mài mòn và bám tốt trên nhiều bề mặt.\n3.Ưu điểm:\n\nThiết kế thời trang, trẻ trung, năng động và dễ phối đồ.\nChất liệu Primeknit ôm chân thoải mái, thoáng khí.\nCông nghệ Boost êm ái, đàn hồi, giảm thiểu chấn thương khi di chuyển.\nĐế ngoài bền bỉ, chống mài mòn và bám tốt trên nhiều bề mặt.\nKhông có chi tiết phản quang, phù hợp với những ai yêu thích sự đơn giản.",
    sku: "RF-1005-ADI",
    material: "Primeknit",
  },

  {
    id: "P1006",
    name: "Converse Aeon Active CX OX 'Egret'",
    brand: "Converse",
    category: "Running",
    price: 1890000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.2,
    reviews: 146,
    isNew: true,
    onSale: false,
    stock: 30,
    gender: "Women",
    image: "../../img/Converse Aeon Active CX OX ‘Egret’/1.png",
    gallery: [
      "../../img/Converse Aeon Active CX OX ‘Egret’/1.png",
      "../../img/Converse Aeon Active CX OX ‘Egret’/2.png",
      "../../img/Converse Aeon Active CX OX ‘Egret’/3.png",
      "../../img/Converse Aeon Active CX OX ‘Egret’/4.png",
    ],
    description_en:
      "The Converse Aeon Active CX OX 'Egret' from Converse is crafted from synthetic leather and mesh, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Giày Converse Aeon Active CX OX ‘Egret’ là một phiên bản phối màu đơn giản và tinh tế của dòng Aeon Active CX. Đôi giày này được lấy cảm hứng từ màu sắc của thiên nhiên, mang đến vẻ ngoài thanh lịch, nhẹ nhàng.\n-Đặc điểm nổi bật:\nKiểu dáng low-top hiện đại: Thân giày thấp, ôm sát chân, thoải mái khi di chuyển.\nMàu sắc Egret: Màu trắng ngà chủ đạo, tạo nên vẻ ngoài thanh lịch, nhẹ nhàng.\nChất liệu cao cấp: Được làm từ da tổng hợp và vải lưới, mang đến cảm giác mềm mại, thoáng khí và dễ dàng vệ sinh.\nLogo Converse Star nổi bật: Tạo điểm nhấn tinh tế, hài hòa với tổng thể màu sắc.\nĐế giữa CX êm ái: Đảm bảo sự êm ái và đàn hồi trên từng bước chân.\nĐế ngoài cao su bền bỉ: Chống trơn trượt, tạo độ bám tốt trên mọi bề mặt.",
    sku: "RF-1006-CON",
    material: "Da tổng hợp và vải lưới",
  },

  {
    id: "P1007",
    name: "Converse Chuck 70 Tortoise 'Black'",
    brand: "Converse",
    category: "Lifestyle",
    price: 1390000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.9,
    reviews: 169,
    isNew: false,
    onSale: false,
    stock: 4,
    gender: "Men",
    image: "../../img/Converse Chuck 70 Tortoise 'Black'/1.jpg",
    gallery: [
      "../../img/Converse Chuck 70 Tortoise 'Black'/1.jpg",
      "../../img/Converse Chuck 70 Tortoise 'Black'/2.jpg",
      "../../img/Converse Chuck 70 Tortoise 'Black'/3.jpg",
      "../../img/Converse Chuck 70 Tortoise 'Black'/4.jpg",
    ],
    description_en:
      "The Converse Chuck 70 Tortoise 'Black' from Converse is crafted from canvas, built for everyday wear with a clean, versatile silhouette in White/Black.",
    description_vi:
      "Converse Chuck 70 Tortoise ‘Black’ là một phiên bản đặc biệt của dòng Chuck 70, kết hợp giữa phong cách cổ điển và các yếu tố hiện đại, tạo nên một diện mạo ấn tượng.\n1.Thiết kế\nMàu Sắc: Mẫu giày này có màu đen chủ đạo, mang đến vẻ ngoài tối giản nhưng sang trọng.\nChi Tiết: Điểm nhấn là họa tiết “tortoise” (vỏ rùa) độc đáo trên một số phần của giày, tạo sự nổi bật và khác biệt so với các phiên bản truyền thống.\n2.Chất liệu\nChất Liệu: Được làm từ vải canvas bền bỉ kết hợp với da tổng hợp, giày không chỉ mang lại độ bền mà còn cảm giác thoải mái khi mang.\n3.Đặc điểm\n-Đế Giày: Đế cao su bền bỉ với thiết kế hoa văn đặc trưng, cung cấp độ bám và ổn định khi di chuyển.\n-Công Nghệ: Hệ thống đệm bên trong giúp tăng cường sự thoải mái và hỗ trợ cho bàn chân, phù hợp cho việc đi bộ cả ngày.\n4.Phong cách\n-Phong Cách Thời Trang: Giày dễ dàng kết hợp với nhiều loại trang phục từ quần jeans, shorts đến váy, tạo nên phong cách trẻ trung và hiện đại.\n-Đối Tượng Sử Dụng: Dành cho cả nam và nữ, hoàn hảo cho những ai yêu thích sự cá tính và phong cách nổi bật.",
    sku: "RF-1007-CON",
    material: "Canvas",
  },
  {
    id: "P1008",
    name: "Converse Chuck Taylor All Star Cruise OX 'Black White'",
    brand: "Converse",
    category: "Lifestyle",
    price: 1800000,
    oldPrice: 2250000,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.6,
    reviews: 192,
    isNew: false,
    onSale: true,
    stock: 36,
    gender: "Unisex",
    image:
      "../../img/Converse Chuck Taylor All Star Cruise OX ‘Black White’/1.jpg",
    gallery: [
      "../../img/Converse Chuck Taylor All Star Cruise OX ‘Black White’/1.jpg",
      "../../img/Converse Chuck Taylor All Star Cruise OX ‘Black White’/2.jpg",
      "../../img/Converse Chuck Taylor All Star Cruise OX ‘Black White’/3.jpg",
      "../../img/Converse Chuck Taylor All Star Cruise OX ‘Black White’/4.jpg",
    ],
    description_en:
      "The Converse Chuck Taylor All Star Cruise OX 'Black White' from Converse is crafted from canvas fabric, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Giày Converse Chuck Taylor All Star Cruise OX ‘Black White’ là một phiên bản tinh tế và năng động của dòng Chuck Taylor cổ điển, mang đến sự kết hợp giữa phong cách thể thao và sự thoải mái.\n1.Thiết kế\nMàu Sắc: Mẫu giày này chủ yếu có màu đen với các chi tiết trắng, tạo ra sự tương phản đẹp mắt và dễ dàng phối hợp với nhiều trang phục.\nChi Tiết: Thiết kế cổ điển với biểu tượng ngôi sao nổi tiếng của Converse, mang lại vẻ ngoài quen thuộc nhưng vẫn đầy mới mẻ.\n2.Chất liệu\nChất Liệu: Được làm từ vải canvas chất lượng cao, giày không chỉ bền bỉ mà còn thoáng khí, tạo cảm giác thoải mái khi mang.\n3.Đặc điểm kỹ thuật\nĐế Giày: Đế cao su bền bỉ với thiết kế hoa văn chữ H, giúp tăng cường độ bám và ổn định khi di chuyển.\nCông Nghệ: Phần lót giày được cải tiến để tăng cường độ êm ái và hỗ trợ cho bàn chân trong suốt cả ngày.\n4.Phong cách\nPhong Cách Thời Trang: Giày dễ dàng kết hợp với nhiều loại trang phục như quần jeans, shorts hoặc váy, tạo nên phong cách trẻ trung và năng động.\nĐối Tượng Sử Dụng: Dành cho cả nam và nữ, hoàn hảo cho những ai yêu thích sự cá tính và phong cách thoải mái.",
    sku: "RF-1008-CON",
    material: "Vải canvas",
  },

  {
    id: "P1009",
    name: "Converse Run Star Hike Low 'Black Gum'",
    brand: "Converse",
    category: "Lifestyle",
    price: 2700000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.3,
    reviews: 215,
    isNew: false,
    onSale: false,
    stock: 39,
    gender: "Women",
    image: "../../img/Converse Run Star Hike Low 'Black Gum'/1.png",
    gallery: [
      "../../img/Converse Run Star Hike Low 'Black Gum'/1.png",
      "../../img/Converse Run Star Hike Low 'Black Gum'/2.png",
      "../../img/Converse Run Star Hike Low 'Black Gum'/3.png",
      "../../img/Converse Run Star Hike Low 'Black Gum'/4.png",
    ],
    description_en:
      "The Converse Run Star Hike Low 'Black Gum' from Converse is crafted from a full-grain leather upper with rugged suede details and metallic gold shimmer, built for everyday wear with a clean, versatile silhouette in Cloud White.",
    description_vi:
      "Ra đời trên sân bóng, giày Samba là biểu tượng kinh điển của phong cách đường phố. \n1.Thiết kế và chất liệu \nLàm việc trên nền vải canvas, Jones cập nhật giao diện tinh tế của Converse Run Star hiện đại bằng cách thêm một lớp đệm TPU trong suốt ở hai bên và mặt sau, hoạt động như một lớp thứ hai cung cấp thêm sự hỗ trợ, độ bền và cấu trúc cho nhiều- Converse Chuck 70 được yêu thích. Chủ yếu là màu kem trong suốt, vẻ ngoài tiện dụng được nâng tầm với các khoen xen kẽ giữa vòng thép bạc và móc lấy cảm hứng từ giày đi bộ đường dài.\n2.Phong cách thiết kế\nVẻ ngoài của thiết kế lần này được hoàn thiện với phần đế giữa phóng đại, gồ ghề hơn nhiều so với kiểu truyền thống, trên đầu là dấu ấn tên của Giám đốc Sáng tạo Dior Homme trên cả hai bên lưỡi gà, cùng nhau hoàn thiện bản collab Converse cao cấp.",
    sku: "RF-1009-CON",
    material:
      "Thân giày bằng da cật với các chi tiết da lộn bụi bặm và nhũ vàng ánh kim",
  },

  {
    id: "P1010",
    name: "MLB BigBall Chunky Embo NY Yankees",
    brand: "MLB",
    category: "Lifestyle",
    price: 4300000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.0,
    reviews: 238,
    isNew: false,
    onSale: false,
    stock: 42,
    gender: "Men",
    image: "../../img/MLB BigBall Chunky Embo NY Yankees/1.png",
    gallery: [
      "../../img/MLB BigBall Chunky Embo NY Yankees/1.png",
      "../../img/MLB BigBall Chunky Embo NY Yankees/2.png",
      "../../img/MLB BigBall Chunky Embo NY Yankees/3.png",
      "../../img/MLB BigBall Chunky Embo NY Yankees/4.png",
    ],
    description_en:
      "The MLB BigBall Chunky Embo NY Yankees from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Giày MLB BigBall Chunky Embo NY Yankees 3ASHBNA3N là một mẫu giày thể thao ấn tượng, mang đến sự kết hợp hoàn hảo giữa phong cách và chức năng. Dưới đây là một số đặc điểm nổi bật:\n1.Thiết kế\nVới kiểu dáng đế dày và hầm hố, giày mang lại cảm giác mạnh mẽ và phong cách hiện đại, rất phù hợp với xu hướng thời trang hiện nay.\n2.Chất liệu\nGiày được làm từ các chất liệu bền bỉ như da tổng hợp hoặc vải chất lượng, giúp tăng cường độ bền và dễ dàng vệ sinh. Chất liệu này cũng giúp giày thoáng khí, tạo cảm giác thoải mái khi mang.\nHọa tiết logo: Logo của đội New York Yankees được thêu hoặc in nổi bật, thể hiện niềm tự hào với đội bóng và tạo điểm nhấn cho thiết kế.\nĐế giày: Phần đế được thiết kế để cung cấp độ bám tốt và hỗ trợ tốt cho bàn chân. Đế giày giúp giảm sốc và mang lại cảm giác dễ chịu khi di chuyển.\nSự thoải mái: Lớp lót êm ái bên trong giày giúp hỗ trợ bàn chân tốt, cho phép bạn đi lại thoải mái suốt cả ngày mà không cảm thấy mệt mỏi.\n3.Phong cách\nMẫu giày này dễ dàng phối hợp với nhiều loại trang phục, từ quần jeans đến quần thể thao, giúp bạn thể hiện phong cách cá nhân một cách tự tin.",
    sku: "RF-1010-MLB",
    material: "Da cao cấp",
  },
  {
    id: "P1011",
    name: "MLB Bigball Chunky Varsity La Dodgers Blue",
    brand: "MLB",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: null,
    colors: ["Cloud White", "Sky Blue"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.7,
    reviews: 261,
    isNew: false,
    onSale: false,
    stock: 45,
    gender: "Unisex",
    image: "../../img/MLB Bigball Chunky Varsity La Dodgers Blue/1.png",
    gallery: [
      "../../img/MLB Bigball Chunky Varsity La Dodgers Blue/1.png",
      "../../img/MLB Bigball Chunky Varsity La Dodgers Blue/2.png",
      "../../img/MLB Bigball Chunky Varsity La Dodgers Blue/3.png",
      "../../img/MLB Bigball Chunky Varsity La Dodgers Blue/4.png",
    ],
    description_en:
      "The MLB Bigball Chunky Varsity La Dodgers Blue from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Blue.",
    description_vi:
      "MLB Bigball Chunky Varsity La Dodgers Blue là một mẫu giày thể thao nổi bật, mang đậm phong cách trẻ trung và hiện đại.\n\nThiết kế và chất liệu\nChất liệu cao cấp: Giày được làm từ vật liệu tổng hợp bền bỉ, mang lại độ bền cao và cảm giác thoải mái khi mang.\nMàu sắc đặc trưng: Tông màu xanh lam nổi bật, biểu trưng cho đội bóng chày Los Angeles Dodgers, tạo nên sự nổi bật và thu hút ánh nhìn.\nĐặc điểm nổi bật\nHọa tiết logo: Logo của LA Dodgers được in rõ nét, thể hiện tình yêu thể thao và sự tự hào về đội bóng.\nĐế chunky: Thiết kế đế dày giúp tạo cảm giác êm ái, giảm áp lực khi di chuyển, đồng thời tạo chiều cao một cách tự nhiên.\nTiện ích\nThiết kế thoáng khí: Giúp giữ cho đôi chân luôn khô thoáng, thoải mái trong suốt thời gian sử dụng.\nĐộ bám tốt: Đế giày được thiết kế đặc biệt để mang lại độ bám vững chắc trên nhiều bề mặt khác nhau, phù hợp cho cả việc đi bộ lẫn các hoạt động thể thao.\nĐối tượng sử dụng\nMẫu giày này phù hợp cho những tín đồ yêu thích sự năng động, cá tính và muốn thể hiện phong cách thời trang thể thao. Đây là lựa chọn tuyệt vời cho các hoạt động hàng ngày, dạo phố hoặc tham gia sự kiện thể thao.\n\nTóm lại, Giày MLB Bigball Chunky Varsity La Dodgers Blue không chỉ mang lại sự thoải mái mà còn thể hiện phong cách trẻ trung, phù hợp cho mọi tín đồ yêu thích thời trang thể thao",
    sku: "RF-1011-MLB",
    material: "Da cao cấp",
  },
  {
    id: "P1012",
    name: "MLB Chunky Classic Dodgers 'White Navy'",
    brand: "MLB",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: 4125000,
    colors: ["Cloud White", "Sky Blue", "Navy"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.4,
    reviews: 284,
    isNew: true,
    onSale: true,
    stock: 48,
    gender: "Women",
    image: "../../img/MLB Chunky Classic Dodgers 'White Navy'/1.png",
    gallery: [
      "../../img/MLB Chunky Classic Dodgers 'White Navy'/1.png",
      "../../img/MLB Chunky Classic Dodgers 'White Navy'/2.png",
      "../../img/MLB Chunky Classic Dodgers 'White Navy'/3.png",
      "../../img/MLB Chunky Classic Dodgers 'White Navy'/4.png",
    ],
    description_en:
      "The MLB Chunky Classic Dodgers 'White Navy' from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Navy.",
    description_vi:
      "MLB Chunky Classic Dodgers ‘White Navy’ là mẫu giày unisex dành cho cả nam và nữ đến từ Hàn Quốc. Với kiểu dáng năng động, thời trang cùng chất liệu cao cấp, đôi giàyMLB Chunky Classic Dodgers ‘White Navy’ mang đến phong cách năng động, được nhiều tín đồ yêu thích.\n1.Chất liệu và màu sắc\nChất liệu: Giày được làm từ chất liệu da tổng hợp cao cấp và vải lưới, tạo nên sự bền bỉ và thoải mái khi sử dụng. Phần da bóng mượt kết hợp với vải lưới giúp giày thoáng khí và dễ dàng làm sạch.\nMàu sắc: Giày có màu chủ đạo là trắng kết hợp với màu xanh navy (màu của đội Dodgers), tạo nên sự đối lập mạnh mẽ nhưng hài hòa, mang lại vẻ ngoài năng động và dễ phối với nhiều loại trang phục.\n2.Thiết kế\nPhong cách Chunky: Giày có thiết kế đế dày (chunky) với các đường nét mạnh mẽ, tạo sự khỏe khoắn và phong cách thời trang streetwear. Đế chunky giúp tăng thêm chiều cao và đồng thời mang lại cảm giác thoải mái khi di chuyển.\nLogo Dodgers: Logo đặc trưng của đội bóng chày Los Angeles Dodgers được in nổi bật trên giày, giúp người mang thể hiện sự yêu thích và ủng hộ đội bóng nổi tiếng này. Đây là một điểm nhấn đặc biệt, thể hiện phong cách thể thao và cá tính.\nHọa tiết Monogram: Các họa tiết monogram (logo MLB) trên phần thân giày và các chi tiết khác giúp tạo sự nhận diện thương hiệu rõ ràng và độc đáo.\n3.Đế giày \nĐế cao su chống trượt: Giày được trang bị đế cao su chất lượng cao, mang lại khả năng bám tốt trên nhiều bề mặt khác nhau. Đế dày giúp tạo sự ổn định và thoải mái khi di chuyển, đồng thời có độ bền cao.\nThiết kế đế: Đế giày có thiết kế độc đáo, với các đường nét giúp tăng cường độ bám và tạo sự chắc chắn cho mỗi bước đi.\n4. Chi tiết và logo:\nLogo MLB và Dodgers: Các logo của MLB và Los Angeles Dodgers được in rõ ràng ở những vị trí nổi bật như lưỡi giày và thân giày, giúp đôi giày trở thành một món đồ thời trang thể thao dễ nhận diện.\nCác chi tiết tinh tế: Các chi tiết may, đường viền và lớp lót giày được gia công tỉ mỉ, tạo sự chắc chắn, bền bỉ và mang lại sự thoải mái cho người sử dụng.\n5. Phong cách:\nGiày MLB Chunky Classic Dodgers ‘White Navy’ 3ASXXA12N-07BLD phù hợp với phong cách streetwear năng động, trẻ trung và hiện đại. Với màu sắc đơn giản nhưng nổi bật, giày dễ dàng phối hợp với nhiều loại trang phục, từ quần jeans, jogger, cho đến áo thun và các bộ đồ thể thao.",
    sku: "RF-1012-MLB",
    material: "Da cao cấp",
  },
  {
    id: "P1013",
    name: "MLB Chunky CLassic Varsity Boston Red Sox",
    brand: "MLB",
    category: "Lifestyle",
    price: 3590000,
    oldPrice: null,
    colors: ["Cloud White", "Crimson"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.1,
    reviews: 307,
    isNew: false,
    onSale: false,
    stock: 0,
    gender: "Men",
    image: "../../img/MLB Chunky Classic Varsity Boston Red Sox/1.png",
    gallery: [
      "../../img/MLB Chunky Classic Varsity Boston Red Sox/1.png",
      "../../img/MLB Chunky Classic Varsity Boston Red Sox/2.png",
      "../../img/MLB Chunky Classic Varsity Boston Red Sox/3.png",
      "../../img/MLB Chunky Classic Varsity Boston Red Sox/4.png",
    ],
    description_en:
      "The MLB Chunky CLassic Varsity Boston Red Sox from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Red.",
    description_vi:
      "MLB Chunky Classic P Boston Red Sox là mẫu giày Unisex dành cho cả nam và nữ đến từ Hàn Quốc đang làm mưa làm gió thời gian qua trên thị trường.\n1.Thiết kế\nKiểu dáng chunky với phần đế dày tạo cảm giác mạnh mẽ và thời trang, rất phù hợp với xu hướng hiện nay.\nHọa tiết logo của đội bóng được in hoặc thêu nổi bật, thể hiện niềm tự hào với đội bóng yêu thích.\n2.Chất liệu\nGiày thường được làm từ chất liệu cao cấp, giúp tăng cường độ bền và dễ dàng bảo trì, đồng thời mang lại cảm giác thoáng khí.\nĐế giày chắc chắn: Phần đế dày giúp cung cấp độ bám tốt và hỗ trợ di chuyển an toàn, cho phép bạn tự tin khi di chuyển.\nSự thoải mái tối ưu: Lớp lót bên trong êm ái hỗ trợ bàn chân, giúp bạn có thể đi lại cả ngày mà không cảm thấy khó chịu.",
    sku: "RF-1013-MLB",
    material: "Da cao cấp",
  },

  {
    id: "P1014",
    name: "MLB Chunky Wide Strike New York Yankees Black",
    brand: "MLB",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: null,
    colors: ["Jet Black", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.8,
    reviews: 330,
    isNew: false,
    onSale: false,
    stock: 4,
    gender: "Unisex",
    image: "../../img/MLB Chunky Wide Strike New York Yankees Black/1.png",
    gallery: [
      "../../img/MLB Chunky Wide Strike New York Yankees Black/1.png",
      "../../img/MLB Chunky Wide Strike New York Yankees Black/2.png",
      "../../img/MLB Chunky Wide Strike New York Yankees Black/3.png",
      "../../img/MLB Chunky Wide Strike New York Yankees Black/4.png",
    ],
    description_en:
      "The MLB Chunky Wide Strike New York Yankees Black from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in Black.",
    description_vi:
      "Giày MLB Chunky Wide Strike New York Yankees Black mang đến một phong cách trẻ trung, hiện đại với nhiều chi tiết nổi bật.\n1.Thiết kế và chất liệu\nChất liệu: Được làm từ chất liệu tổng hợp bền bỉ, giày vừa đảm bảo sự chắc chắn lại vừa tạo cảm giác thoải mái cho người mang.\nMàu sắc: Tông màu đen chủ đạo không chỉ dễ phối đồ mà còn tạo vẻ sang trọng, cá tính.\n2.Đặc điểm nổi bật\nHọa tiết logo: Biểu tượng của đội bóng chày New York Yankees được thiết kế tinh tế, thể hiện niềm đam mê thể thao.\nĐế chunky: Đế dày và rộng không chỉ giúp tạo cảm giác êm ái khi di chuyển mà còn tạo chiều cao, nâng tầm phong cách.\nTiện ích\nThiết kế thoáng khí: Giúp giữ cho đôi chân luôn khô thoáng, dễ chịu trong suốt quá trình sử dụng.\nĐộ bám tốt: Đế giày được thiết kế để mang lại độ bám vững chắc trên nhiều loại bề mặt.\nĐối tượng sử dụng\nGiày phù hợp với những ai yêu thích sự năng động, thời trang và đam mê thể thao. Đây là lựa chọn lý tưởng cho các hoạt động hàng ngày, dạo phố hoặc tham gia các sự kiện thể thao",
    sku: "RF-1014-MLB",
    material: "Da cao cấp",
  },

  {
    id: "P1015",
    name: "MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy",
    brand: "MLB",
    category: "Lifestyle",
    price: 2600000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.5,
    reviews: 353,
    isNew: false,
    onSale: false,
    stock: 17,
    gender: "Women",
    image:
      "../../img/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/1.png",
    gallery: [
      "../../img/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/1.png",
      "../../img/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/2.png",
      "../../img/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/3.png",
      "../../img/MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy/4.png",
    ],
    description_en:
      "The MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy from MLB is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Giày MLB Korea Chunky Liner Denim Classic Mono New York Yankees Navy à một thiết kế nổi bật trong bộ sưu tập của MLB Korea, kết hợp giữa phong cách thể thao và thời trang hiện đại.\n  .Đặc điểm nổi bật\n– Chất liệu: Giày được làm từ chất liệu denim (vải jeans) với tông màu xanh navy chủ đạo, mang lại cảm giác thời trang và cổ điển.\n– Thiết kế: Phần thân giày có form dáng chunky (to bản, dày dặn) – một xu hướng đang rất phổ biến, với các đường nét mạnh mẽ và khỏe khoắn.\n– Logo: Trên thân giày có logo đội bóng chày **New York Yankees** được in màu trắng, tạo sự tương phản nổi bật trên nền denim.\n– Đế giày: Đế cao su dày, bám tốt, mang lại sự thoải mái và chắc chắn khi di chuyển, đồng thời tăng chiều cao đáng kể. Kiểu dáng chunky giúp đôi giày vừa năng động vừa hợp thời trang.\n– Phong cách: Phù hợp để phối đồ casual (thoải mái), street style, tạo phong cách cá tính, trẻ trung.",
    sku: "RF-1015-MLB",
    material: "Da cao cấp",
  },

  {
    id: "P1016",
    name: "New Balance 530 White Silver Green",
    brand: "New Balance",
    category: "Lifestyle",
    price: 2700000,
    oldPrice: 3375000,
    colors: ["Forest Green", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.2,
    reviews: 376,
    isNew: false,
    onSale: true,
    stock: 20,
    gender: "Men",
    image: "../../img/New Balance 530 White Silver Green/1.png",
    gallery: [
      "../../img/New Balance 530 White Silver Green/1.png",
      "../../img/New Balance 530 White Silver Green/2.png",
      "../../img/New Balance 530 White Silver Green/3.png",
      "../../img/New Balance 530 White Silver Green/4.png",
    ],
    description_en:
      "The New Balance 530 White Silver Green from New Balance is crafted from leather and mesh fabric, built for everyday wear with a clean, versatile silhouette in Green/Silver.",
    description_vi:
      "Đôi giày New Balance 530 ‘White Silver Green’ là sự kết hợp tinh tế giữa phong cách cổ điển và nét hiện đại, phù hợp cho những ai yêu thích sự đơn giản nhưng vẫn nổi bật.\n\nẤn tượng đầu tiên đến từ tông màu trắng chủ đạo – mang lại cảm giác sạch sẽ, dễ phối đồ với nhiều trang phục khác nhau. Điểm nhấn nổi bật là các chi tiết màu xanh lá nhạt (green) và bạc (silver) được bố trí khéo léo ở các vị trí như logo chữ “N” hai bên thân giày, phần gót và đế ngoài, tạo nên sự hài hòa về màu sắc mà vẫn đủ sức thu hút ánh nhìn.\n\nThiết kế của New Balance 530 lấy cảm hứng từ dòng giày chạy bộ cổ điển những năm 90, với phần đế khá dày, tạo sự chắc chắn và thoải mái khi di chuyển. Phần thân giày sử dụng chất liệu da tổng hợp và lưới thoáng khí, giúp tăng độ bền và mang lại cảm giác thông thoáng cho bàn chân trong suốt ngày dài hoạt động.\n\nĐế giày làm từ cao su có độ bám tốt, chống trơn trượt hiệu quả trên nhiều bề mặt. Đặc biệt, lớp đệm midsole nhẹ và đàn hồi giúp giảm chấn khi di chuyển, đem lại trải nghiệm êm ái và dễ chịu.\n\nNew Balance 530 ‘White Silver Green’ không chỉ là một đôi giày thời trang mà còn là người bạn đồng hành tin cậy cho những ai tìm kiếm sự thoải mái và phong cách giản dị nhưng tinh tế trong từng bước chân.",
    sku: "RF-1016-NEW",
    material: "Da và vải lưới",
  },
  {
    id: "P1017",
    name: "New Balance 550 'White Mint Green'",
    brand: "New Balance",
    category: "Lifestyle",
    price: 3000000,
    oldPrice: null,
    colors: ["Cloud White", "Sky Blue"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.9,
    reviews: 399,
    isNew: false,
    onSale: false,
    stock: 23,
    gender: "Unisex",
    image: "../../img/New Balance 550 'White Mint Green'/1.png",
    gallery: [
      "../../img/New Balance 550 'White Mint Green'/1.png",
      "../../img/New Balance 550 'White Mint Green'/2.png",
      "../../img/New Balance 550 'White Mint Green'/3.png",
      "../../img/New Balance 550 'White Mint Green'/4.png",
    ],
    description_en:
      "The New Balance 550 'White Mint Green' from New Balance is crafted from premium animal leather, built for everyday wear with a clean, versatile silhouette in White/Green.",
    description_vi:
      "Giày New Balance 550 ‘White Mint Green’  là một phiên bản đặc biệt trong dòng giày New Balance 550, mang đến sự kết hợp giữa phong cách thể thao và sự tươi mới.\n1.Thiết kế và chất liệu\nPhần trên của giày được làm từ chất liệu da và vải cao cấp, tạo cảm giác thoáng khí và độ bền. Màu sắc chủ đạo của giày là màu trắng kết hợp với màu xanh mint (xanh lá cây nhạt), tạo nên vẻ ngoài tươi mới và trẻ trung.\n2.Phong cách thiết kế\nGiày New Balance 550 ‘White Mint Green’có thiết kế đơn giản và hiện đại. Logo New Balance được đặt ở các vị trí khác nhau trên giày, tạo điểm nhấn và thể hiện thương hiệu.\n\nGiày New Balance 550 ‘White Mint Green’  mang đến sự kết hợp hoàn hảo giữa phong cách và thoải mái. Đôi giày này không chỉ là một sản phẩm thể thao chất lượng, mà còn là biểu tượng của sự tươi mới và phong cách trong thế giới thời trang.",
    sku: "RF-1017-NEW",
    material: "Da thú",
  },

  {
    id: "P1018",
    name: "Air Jordan 1 Low 'Grey White'",
    brand: "Nike",
    category: "Basketball",
    price: 3000000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.6,
    reviews: 422,
    isNew: true,
    onSale: false,
    stock: 26,
    gender: "Women",
    image: "../../img/Air Jordan 1 Low 'Grey White'/1.png",
    gallery: [
      "../../img/Air Jordan 1 Low 'Grey White'/1.png",
      "../../img/Air Jordan 1 Low 'Grey White'/2.png",
      "../../img/Air Jordan 1 Low 'Grey White'/3.png",
      "../../img/Air Jordan 1 Low 'Grey White'/4.png",
    ],
    description_en:
      "The Air Jordan 1 Low 'Grey White' from Nike is crafted from leather, built for everyday wear with a clean, versatile silhouette in Grey White.",
    description_vi:
      "Giày sneaker ngày nay không chỉ đơn thuần là một sản phẩm phục vụ cho thể thao, mà còn là một tuyên ngôn về phong cách sống, cá tính và gu thẩm mỹ. Trong vô vàn những đôi giày nổi bật trên thị trường, Air Jordan 1 Low ‘Grey White’ nổi lên như một biểu tượng của sự tối giản, tinh tế và đầy cuốn hút. Air Jordan 1 là dòng giày huyền thoại gắn liền với tên tuổi của huyền thoại bóng rổ Michael Jordan. \n1.Thiết kế\nNike Air Jordan 1 Low ‘Grey White’  sở hữu phối màu trung tính hiện đại, mang đến cảm giác thanh lịch nhưng vẫn giữ được nét thể thao đặc trưng của dòng Jordan 1. Thiết kế kết hợp giữa hai tông xám nhạt và trắng tạo nên vẻ ngoài tối giản, dễ phối đồ và phù hợp với nhiều phong cách khác nhau\n2.Chất liệu\nPhần upper bằng da cao cấp mang lại độ bền chắc cùng khả năng ôm chân thoải mái. Logo Swoosh màu xám nổi bật trên nền trắng, đi kèm biểu tượng Air Jordan Wings ở gót giày, tạo điểm nhấn quen thuộc của dòng AJ1.\nĐế giày sử dụng đệm Air nhẹ êm, hỗ trợ bước đi linh hoạt và mang lại cảm giác thoải mái khi mang cả ngày. Đế ngoài cao su với các rãnh chống trượt đảm bảo độ bám tốt trên nhiều bề mặt.",
    sku: "RF-1018-NIK",
    material: "Da",
  },

  {
    id: "P1019",
    name: "Nike Air Force 1 White",
    brand: "Nike",
    category: "Lifestyle",
    price: 2500000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.3,
    reviews: 445,
    isNew: false,
    onSale: false,
    stock: 29,
    gender: "Men",
    image: "../../img/Nike Air Force 1 White/1.png",
    gallery: [
      "../../img/Nike Air Force 1 White/1.png",
      "../../img/Nike Air Force 1 White/2.png",
      "../../img/Nike Air Force 1 White/3.png",
      "../../img/Nike Air Force 1 White/4.png",
    ],
    description_en:
      "The Nike Air Force 1 White from Nike is crafted from smooth leather material, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Giày Nike Air Force 1 ‘White’  là một trong những đôi giày sneaker phổ biến nhất trên thế giới. Đôi giày được ra mắt lần đầu tiên vào năm 1982 và nhanh chóng trở thành biểu tượng của phong cách thời trang đường phố.\n1.Thiết kế và chất liệu\nGiày Nike Air Force 1 ‘White’ có thiết kế đơn giản nhưng tinh tế với thân giày bằng da trắng trơn. Logo Swoosh và họa tiết chữ “Air Force” màu đen nổi bật trên nền trắng, tạo điểm nhấn ấn tượng. Phần đế giữa bằng bọt Nike Air mang lại cảm giác thoải mái, êm ái khi di chuyển.\n2.Phong cách\nGiày Nike Air Force 1 ‘White’ phù hợp với nhiều phong cách thời trang khác nhau, từ thể thao, đường phố đến công sở. Đôi giày có thể phối với nhiều loại trang phục khác nhau, từ quần jean, quần short đến váy hoặc đầm.",
    sku: "RF-1019-NIK",
    material: "Chất liệu da trơn",
  },

  {
    id: "P1020",
    name: "Nike Air Max 1 Premium 'Black and Playful Pink'",
    brand: "Nike",
    category: "Running",
    price: 4290000,
    oldPrice: 5362000,
    colors: ["Jet Black", "Pink"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.0,
    reviews: 468,
    isNew: false,
    onSale: true,
    stock: 32,
    gender: "Unisex",
    image: "../../img/Nike Air Max 1 Premium 'Black and Playful Pink'/1.png",
    gallery: [
      "../../img/Nike Air Max 1 Premium 'Black and Playful Pink'/1.png",
      "../../img/Nike Air Max 1 Premium 'Black and Playful Pink'/2.png",
      "../../img/Nike Air Max 1 Premium 'Black and Playful Pink'/3.png",
      "../../img/Nike Air Max 1 Premium 'Black and Playful Pink'/4.png",
    ],
    description_en:
      "The Nike Air Max 1 Premium 'Black and Playful Pink' from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in Black/Playful Pink.",
    description_vi:
      "Giày Nike Air Max 1 Premium ‘Black and Playful Pink’là một phiên bản đặc biệt của mẫu giày Nike Air Max 1 huyền thoại, nổi bật với thiết kế kết hợp giữa màu sắc mạnh mẽ và trẻ trung. Được biết đến với thiết kế đế khí Air Max đặc trưng, đôi giày này mang lại sự thoải mái, hỗ trợ trong từng bước đi và vẫn giữ được sự phong cách và nổi bật. Dưới đây là những điểm nổi bật của mẫu giày này:\n1. Thiết kế màu sắc:\n-Màu sắc chủ đạo là Black (đen) kết hợp với các chi tiết Playful Pink (hồng tươi), tạo nên sự tương phản mạnh mẽ và nổi bật. Màu đen mang đến vẻ ngoài cổ điển, thanh lịch, trong khi màu hồng tươi tạo điểm nhấn vui nhộn và trẻ trung, khiến đôi giày này trở nên ấn tượng và cá tính.\n2. Chất liệu\nUpper: Phần trên của giày được làm từ một sự kết hợp giữa da cao cấp, vải lưới (mesh) và chất liệu tổng hợp. Các chất liệu này không chỉ mang lại sự thoáng khí mà còn tăng cường độ bền, giúp giày nhẹ và dễ dàng di chuyển trong mọi tình huống.\nLót giày: Lót giày mềm mại và thoải mái, giúp giữ cho đôi chân luôn khô ráo và dễ chịu trong suốt quá trình di chuyển.\n3. Công nghệ đệm Air Max:\n-Đế khí Air Max: Công nghệ Air Max đặc trưng của Nike giúp mang lại cảm giác êm ái và thoải mái khi tiếp xúc với mặt đất. Phần đế khí ở đế giữa giúp giảm chấn và cung cấp sự hỗ trợ tuyệt vời trong mọi hoạt động di chuyển, đồng thời giúp đôi giày nhẹ và dễ dàng chịu được tác động từ mặt đất.\n-Đệm EVA: Đế giữa cũng được trang bị đệm EVA, một vật liệu nhẹ và bền, giúp giảm trọng lượng giày mà không làm mất đi sự ổn định.\n4. Đế ngoài:\n-Cao su bền bỉ: Đế ngoài của giày sử dụng cao su chất lượng cao với các họa tiết vân giúp tăng cường độ bám và độ ổn định khi di chuyển. Thiết kế đế này giúp bạn dễ dàng kiểm soát và di chuyển linh hoạt trên các bề mặt khác nhau.\n-Họa tiết vân: Đế ngoài có các họa tiết vân đa chiều, giúp tối ưu hóa độ bám và khả năng kiểm soát khi di chuyển.\n5. Phong cách thiết kế:\n-Độ bền cao: Giày được làm từ các chất liệu chất lượng cao, đảm bảo độ bền lâu dài trong suốt quá trình sử dụng. Với thiết kế chắc chắn và các công nghệ tiên tiến, đôi giày này phù hợp với những ai yêu thích sự bền bỉ và thoải mái.\n-Tính linh hoạt: Đôi giày được thiết kế để hỗ trợ mọi chuyển động, giúp người mang dễ dàng di chuyển và thay đổi hướng nhanh chóng mà không cảm thấy cản trở.",
    sku: "RF-1020-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1021",
    name: "Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'",
    brand: "Nike",
    category: "Basketball",
    price: 2990000,
    oldPrice: null,
    colors: ["Cloud White", "Forest Green", "Slate Grey"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.7,
    reviews: 11,
    isNew: false,
    onSale: false,
    stock: 4,
    gender: "Women",
    image:
      "../../img/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/1.png",
    gallery: [
      "../../img/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/1.png",
      "../../img/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/2.png",
      "../../img/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/3.png",
      "../../img/Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey'/4.png",
    ],
    description_en:
      "The Nike Blazer Mid '77 Vintage 'Recycled Wool Pack – White Light Smoke Grey' from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White/Light Smoke Grey-Electric Green.",
    description_vi:
      "Nike Blazer Mid ’77 Vintage ‘Recycled Wool Pack – White Light Smoke Grey’ mang đến sự tái hiện bền vững của một trong những đôi giày bóng rổ đầu tiên của thương hiệu.\n1.Thiết kế\nNike Blazer Mid 77 Vintage Recycled Wool có phần thân trên bằng da trắng, các chi tiết màu xám nhạt tương phản với phần thân giày.\nĐiểm đặc biệt của dòng này là logo Swoosh màu đen tái chế .\n2.Chất liệu\n Da tổng hợp màu trắng tái chế được sử dụng ở mặt trên, được tạo điểm nhấn bằng lưỡi xốp lộ ra ngoài và dấu Swoosh bên hông được tạo hình bằng nỉ tái chế 100%. \n Các vật liệu tái chế bổ sung được áp dụng cho lớp lót giày màu Volt và đế ngoài Nike Grind, bao gồm cao su phế liệu được thu thập từ sàn nhà máy.     \nNhưng chúng tôi nghĩ phần tuyệt vời nhất của đôi giày này là bạn không thể nhận ra nó được làm từ vật liệu tái chế chỉ bằng cách nhìn vào nó. Nó trông giống như bất kỳ đôi Nike Blazer Mid 77 Vintage nào khác trong khi chứa các vật liệu tốt hơn cho môi trường.",
    sku: "RF-1021-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1022",
    name: "Nike Dunk Low 'Panda' 2025",
    brand: "Nike",
    category: "Lifestyle",
    price: 2900000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.4,
    reviews: 34,
    isNew: false,
    onSale: false,
    stock: 38,
    gender: "Men",
    image: "../../img/Nike Dunk Low 'Panda' 2025/1.png",
    gallery: [
      "../../img/Nike Dunk Low 'Panda' 2025/1.png",
      "../../img/Nike Dunk Low 'Panda' 2025/2.png",
      "../../img/Nike Dunk Low 'Panda' 2025/3.png",
      "../../img/Nike Dunk Low 'Panda' 2025/4.png",
    ],
    description_en:
      "The Nike Dunk Low 'Panda' 2025 from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Nike Dunk Low Panda 2025 là phiên bản mới của mẫu giày Nike Dunk Low nổi tiếng, với một trong những thiết kế được yêu thích nhất trong dòng Dunk. Phiên bản Panda mang đến sự kết hợp màu sắc đơn giản nhưng rất nổi bật, tạo nên một phong cách dễ phối đồ và cực kỳ thời trang. Dưới đây là mô tả chi tiết về mẫu giày này:\n\n1.Màu sắc và chất liệu:\nMàu sắc: Giày có sự kết hợp của màu đen và trắng (hình ảnh “panda” được gợi lên từ sự kết hợp này), với màu đen chủ yếu xuất hiện ở phần thân giày, logo Nike Swoosh và phần gót giày, trong khi màu trắng được sử dụng cho phần mũi giày, lưỡi gà và đế giày. Sự đối lập mạnh mẽ giữa đen và trắng tạo nên một kiểu dáng đơn giản nhưng rất nổi bật.\n2.Chất liệu: Giày được làm từ chất liệu da cao cấp, mang lại độ bền và cảm giác thoải mái khi mang. Phần da lộn cũng được sử dụng ở một số khu vực, tạo thêm texture cho giày và tăng độ bền.\nThiết kế và cấu trúc:\n3.Form giày: Nike Dunk Low mang thiết kế cổ điển với phần cổ thấp, giúp người mang có sự linh hoạt và thoải mái khi di chuyển. Kiểu dáng này làm cho giày dễ dàng phối đồ và thích hợp cho nhiều dịp sử dụng.\nLogo: Logo Nike Swoosh nổi bật với màu đen trên nền trắng, tạo điểm nhấn rõ ràng và giúp giày thêm phần mạnh mẽ và cá tính. Các chi tiết khác của giày, như lưỡi gà và gót giày, đều rất đơn giản, giữ nguyên vẻ đẹp cổ điển của Dunk.\nĐế giày: Đế giày có màu trắng, được làm từ cao su với các rãnh vân nổi, giúp tăng độ bám và sự ổn định khi di chuyển trên nhiều bề mặt. Đế giày không chỉ bền mà còn rất thoải mái khi sử dụng.\n4.Ứng dụng và phong cách:\nPhong cách: Nike Dunk Low Panda 2025 là đôi giày cực kỳ dễ phối đồ. Với sự kết hợp giữa màu đen và trắng, đôi giày này phù hợp với nhiều phong cách khác nhau, từ thể thao đến streetwear hay casual. Bạn có thể kết hợp giày với quần jeans, quần thể thao, áo thun, hoodie, hoặc áo khoác, tạo nên một vẻ ngoài năng động và trẻ trung.\nSự thoải mái: Thiết kế đệm giày êm ái và cấu trúc vừa vặn giúp giày mang lại sự thoải mái tối đa khi mang lâu dài, rất phù hợp cho các hoạt động thể thao",
    sku: "RF-1022-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1023",
    name: "Nike Invincible 3 'Pink Foam'",
    brand: "Nike",
    category: "Running",
    price: 6300000,
    oldPrice: null,
    colors: ["Pink", "Slate Grey"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.1,
    reviews: 57,
    isNew: false,
    onSale: false,
    stock: 41,
    gender: "Unisex",
    image: "../../img/Nike Invincible 3 'Pink Foam'/1.png",
    gallery: [
      "../../img/Nike Invincible 3 'Pink Foam'/1.png",
      "../../img/Nike Invincible 3 'Pink Foam'/2.png",
      "../../img/Nike Invincible 3 'Pink Foam'/3.png",
      "../../img/Nike Invincible 3 'Pink Foam'/4.png",
    ],
    description_en:
      "The Nike Invincible 3 'Pink Foam' from Nike is crafted from Flyknit fabric, built for everyday wear with a clean, versatile silhouette in Pink.",
    description_vi:
      "Giày Nike Invincible 3 ‘Pink Foam’  là một đôi giày chạy bộ tối ưu cho người chạy bộ đường dài. Giày có thiết kế hiện đại, thời trang với màu sắc nổi bật.\n1.Chất liệu\nGiày được làm từ chất liệu Flyknit nhẹ và thoáng khí, mang lại cảm giác thoải mái và linh hoạt khi chạy. Phần đệm ZoomX ở gót chân và mũi chân cung cấp khả năng đệm và phản hồi cao, giúp giảm tác động lên cơ thể và mang lại cảm giác êm ái khi chạy\n\n2.Một số đặc điểm nổi bật của sản phẩm:\n\nChất liệu Flyknit nhẹ và thoáng khí\nĐệm ZoomX ở gót chân và mũi chân\nHệ thống Flywire giúp giữ chân chắc chắn\nĐế ngoài cao su bền bỉ\n\nGiày Nike Invincible 3  là một lựa chọn tuyệt vời cho những người chạy bộ đường dài đang tìm kiếm một đôi giày thoải mái, linh hoạt và hỗ trợ tốt.",
    sku: "RF-1023-NIK",
    material: "Vải Flyknit",
  },

  {
    id: "P1024",
    name: "Nike SB Dunk Low Pro Be True",
    brand: "Nike",
    category: "Lifestyle",
    price: 6300000,
    oldPrice: 7875000,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.8,
    reviews: 80,
    isNew: true,
    onSale: true,
    stock: 44,
    gender: "Women",
    image: "../../img/Nike SB Dunk Low Pro Be True/1.png",
    gallery: [
      "../../img/Nike SB Dunk Low Pro Be True/1.png",
      "../../img/Nike SB Dunk Low Pro Be True/2.png",
      "../../img/Nike SB Dunk Low Pro Be True/3.png",
      "../../img/Nike SB Dunk Low Pro Be True/4.png",
    ],
    description_en:
      "The Nike SB Dunk Low Pro Be True from Nike is crafted from premium leather, built for everyday wear with a clean, versatile silhouette in White.",
    description_vi:
      "Nike SB Dunk Low Pro Be Truelà một sản phẩm thuộc dòng giày Dunk của Nike, được phát hành vào năm 2022. Đây là một thiết kế đặc biệt và mang tính biểu tượng, với gam màu chủ đạo là đen và trắng, cùng với các chi tiết sặc sỡ.\n1.Thiết kế \n-Thiết kế này có màu đen chủ đạo trên toàn thân giày, kết hợp với các chi tiết màu trắng và xanh dương, tạo nên sự độc đáo và sặc sỡ.\n-Bên cạnh đó, các chi tiết nổi bật trên đôi giày như swoosh logo ở hai bên thân giày hay tên thương hiệu Nike được in ở gót giày cũng là điểm nhấn thu hút ánh nhìn.\n2.Chất liệu\n-Đôi giày này có chất liệu da cao cấp kết hợp với lớp vải mềm mại, mang lại sự thoải mái và bền bỉ cho người sử dụng. \n-Đi kèm với đó là phần đế giày được làm bằng cao su chất lượng cao, mang lại độ bền và độ bám tốt trên nhiều loại mặt đất khác nhau. \n-Những chi tiết như lỗ thông hơi phần upper và thiết kế đế giày êm ái, cùng với đệm khí Nike Air giúp giảm thiểu áp lực cho đôi chân khi di chuyển nên sẽ giúp bạn cảm thấy thoải mái và dễ chịu hơn trong khi tập luyện.\n\nCó thể nói, dòng giày Nike Dunk Low có thiết kế đơn giản, thanh lịch và tông màu chủ đạo phù hợp với nhiều loại trang phục khác nhau. Với sự linh hoạt trong cách phối đồ, người dùng có thể kết hợp giày này với quần jean, quần shorts, váy đầm hay đồ bộ thể thao. Điều này mang đến cho người dùng sự tiện dụng và thoải mái khi di chuyển từ công việc đến cuộc hẹn hò hay các hoạt động thể thao như đi bộ, chạy bộ, đá banh, …",
    sku: "RF-1024-NIK",
    material: "Da cao cấp",
  },

  {
    id: "P1025",
    name: "Nike Zoom Vomero 5 'Yankees'",
    brand: "Nike",
    category: "Running",
    price: 4200000,
    oldPrice: null,
    colors: ["Cloud White", "Slate Grey"],
    sizes: [39, 40, 41, 42, 44],
    rating: 4.5,
    reviews: 103,
    isNew: false,
    onSale: false,
    stock: 47,
    gender: "Men",
    image: "../../img/Nike Zoom Vomero 5 'Yankees'/1.png",
    gallery: [
      "../../img/Nike Zoom Vomero 5 'Yankees'/1.png",
      "../../img/Nike Zoom Vomero 5 'Yankees'/2.png",
      "../../img/Nike Zoom Vomero 5 'Yankees'/3.png",
      "../../img/Nike Zoom Vomero 5 'Yankees'/4.png",
    ],
    description_en:
      "The Nike Zoom Vomero 5 'Yankees' from Nike is crafted from mesh and synthetic leather, built for everyday wear with a clean, versatile silhouette in Silver/White.",
    description_vi:
      "Giày Nike Zoom Vomero 5 ‘Yankees’  là một trong những mẫu giày thể thao nổi bật của dòng Nike Zoom Vomero, được thiết kế với cảm hứng từ đội bóng chày New York Yankees. Với sự kết hợp giữa công nghệ tiên tiến và thiết kế cổ điển, giày mang lại sự thoải mái, hỗ trợ tối đa cho người sử dụng trong các hoạt động thể thao hoặc dạo phố. Dưới đây là mô tả chi tiết về sản phẩm:\n\n1. Màu sắc:\n‘Yankees’: Đôi giày này có một màu sắc đặc biệt lấy cảm hứng từ màu sắc của đội bóng chày nổi tiếng New York Yankees, với xanh navy (màu chủ đạo) kết hợp với các chi tiết màu trắng và bạc. Màu sắc này mang đến một vẻ ngoài thể thao, lịch lãm và dễ dàng phối hợp với nhiều trang phục khác nhau, từ đồ thể thao cho đến đồ casual.\n2. Chất liệu:\nUpper: Phần upper của giày được làm từ chất liệu vải lưới (mesh) kết hợp với da tổng hợp (synthetic leather). Chất liệu này giúp giày có độ thoáng khí tốt, giúp bàn chân luôn khô ráo và thoải mái trong suốt quá trình vận động, đồng thời tạo sự bền bỉ và độ bám tốt.\nĐế giữa: Giày sử dụng công nghệ Nike Zoom trong đế giữa, với các lớp đệm Zoom Air giúp giảm sốc và mang lại cảm giác êm ái khi di chuyển. Công nghệ này hỗ trợ các vận động viên và người dùng trong các hoạt động có cường độ cao như chạy bộ, tập luyện thể thao.\nĐế ngoài: Đế giày được làm từ cao su bền bỉ với thiết kế các rãnh giúp tăng độ bám và ổn định khi di chuyển trên nhiều bề mặt khác nhau, từ sân cứng đến các bề mặt gồ ghề.\n3. Thiết kế:\nForm Fit: Giày Nike Zoom Vomero 5 ‘Yankees’ có thiết kế ôm chân vừa vặn, tạo cảm giác thoải mái và hỗ trợ ổn định trong suốt quá trình di chuyển. Cổ giày thấp giúp tăng sự linh hoạt cho cổ chân, nhưng vẫn đảm bảo sự bảo vệ và hỗ trợ cần thiết.\nChi tiết trang trí: Logo Nike Swoosh nổi bật được in ở hai bên hông giày, đồng thời các chi tiết Yankees như hình ảnh logo đội bóng được thêu trên phần gót giày, mang đến điểm nhấn đặc trưng và sự kết nối với đội bóng chày huyền thoại.\n4. Phong cách:\nThể thao và hiện đại: Giày mang đến phong cách thể thao đặc trưng với sự kết hợp của màu s",
    sku: "RF-1025-NIK",
    material: "Lưới và Da tổng hợp",
  },

  {
    id: "P1026",
    name: "PUMA Roma 68 Revival 'Black Gold'",
    brand: "PUMA",
    category: "Lifestyle",
    price: 3300000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White", "Gold"],
    sizes: [38, 39, 40, 41, 43, 44],
    rating: 4.2,
    reviews: 126,
    isNew: false,
    onSale: false,
    stock: 0,
    gender: "Unisex",
    image: "../../img/PUMA Roma 68 Revival 'Black Gold'/1.png",
    gallery: [
      "../../img/PUMA Roma 68 Revival 'Black Gold'/1.png",
      "../../img/PUMA Roma 68 Revival 'Black Gold'/2.png",
      "../../img/PUMA Roma 68 Revival 'Black Gold'/3.png",
      "../../img/PUMA Roma 68 Revival 'Black Gold'/4.png",
    ],
    description_en:
      "The PUMA Roma 68 Revival 'Black Gold' from PUMA is crafted from premium leather combining both suede and smooth leather finishes, built for everyday wear with a clean, versatile silhouette in Black/White/Gold.",
    description_vi:
      "PUMA Palermo Wide Lace SD ‘Black White Gold’ là một phiên bản đặc biệt của dòng PUMA Palermo, mang đến sự kết hợp hoàn hảo giữa thiết kế cổ điển và các yếu tố hiện đại, tạo nên một đôi giày vừa thanh lịch, vừa mạnh mẽ.\nPhiên bản này không chỉ thể hiện phong cách thể thao mà còn nổi bật với các chi tiết sang trọng và cao cấp, rất phù hợp cho những ai yêu thích sự tinh tế trong thời trang.\n1.Chất liệu\n-Upper (Phần trên): Giày sử dụng chất liệu da cao cấp, kết hợp giữa da lộn và da trơn. Da lộn mang lại sự mềm mại và cảm giác sang trọng, trong khi da trơn giúp tăng độ bền và sự dễ dàng trong việc chăm sóc giày. Đây là sự pha trộn hoàn hảo giữa chất liệu bền bỉ và tính thẩm mỹ cao.\n-Lót giày: Lót giày mềm mại và thoáng khí, giúp đôi chân của bạn luôn khô ráo và thoải mái trong suốt quá trình sử dụng.\n2.Thiết kế phối màu\n-Màu sắc chủ đạo: Phiên bản này sử dụng bộ ba màu sắc cổ điển nhưng cực kỳ ấn tượng: Black (đen), White (trắng) và Gold (vàng kim). Phần thân giày có màu đen, trong khi các chi tiết như logo PUMA, sọc trang trí, và các đường chỉ may sử dụng màu trắng và vàng kim, tạo sự tương phản nổi bật.\n-Chi tiết vàng kim: Những chi tiết vàng kim không chỉ tạo điểm nhấn sang trọng mà còn làm tăng vẻ nổi bật của đôi giày. Logo PUMA và phần gót giày có các chi tiết vàng giúp làm nổi bật tổng thể thiết kế, mang đến vẻ ngoài tinh tế và cao cấp.\n3.Cấu trúc và thiết kế:\n-Hình dáng low-top: Giày có thiết kế cổ thấp (low-top), mang đến sự linh hoạt tối đa trong mọi hoạt động. Với kiểu dáng này, giày không chỉ phù hợp cho những hoạt động thể thao nhẹ mà còn là lựa chọn tuyệt vời cho những buổi dạo phố hoặc các sự kiện casual.\n-Wide Lace (Dây giày bản rộng): Một điểm đặc biệt của mẫu giày này là dây giày bản rộng, giúp tạo ra một vẻ ngoài khác biệt và hiện đại hơn so với các mẫu giày có dây giày mảnh. Dây giày rộng cũng giúp tăng cường độ ôm sát và sự vừa vặn của giày trên chân.\n4.Phong cách và cảm hứng thiết kế:\n-Phong cách cổ điển với một chút hiện đại: PUMA Palermo luôn mang đến một thiết kế thể thao cổ điển, nhưng phiên bản này lại được làm mới với các chi tiết hiện đại, đặc biệt là sự xuất hiện của dây giày bản rộng và màu sắc sang trọng.",
    sku: "RF-1026-PUM",
    material: "Da cao cấp được kết hợp giữa da lộn và da trơn",
  },

  {
    id: "P1027",
    name: "Puma Speedcat OG 'Dark Brown'",
    brand: "PUMA",
    category: "Lifestyle",
    price: 4400000,
    oldPrice: null,
    colors: ["Brown", "Slate Grey"],
    sizes: [38, 39, 40, 42, 43, 44],
    rating: 4.9,
    reviews: 149,
    isNew: false,
    onSale: false,
    stock: 13,
    gender: "Women",
    image: "../../img/Puma Speedcat OG 'Dark Brown'/1.png",
    gallery: [
      "../../img/Puma Speedcat OG 'Dark Brown'/1.png",
      "../../img/Puma Speedcat OG 'Dark Brown'/2.png",
      "../../img/Puma Speedcat OG 'Dark Brown'/3.png",
      "../../img/Puma Speedcat OG 'Dark Brown'/4.png",
    ],
    description_en:
      "The Puma Speedcat OG 'Dark Brown' from PUMA is crafted from synthetic leather and mesh fabric, built for everyday wear with a clean, versatile silhouette in Dark Brown.",
    description_vi:
      "Puma Speedcat OG ‘Dark Brown’  là một mẫu giày thể thao cổ điển thuộc dòng Speedcat của Puma, mang đậm phong cách retro với thiết kế đơn giản nhưng đầy mạnh mẽ. \nMẫu giày này kết hợp giữa tính năng thể thao và vẻ ngoài thanh lịch, rất phù hợp cho những ai yêu thích sự thoải mái nhưng vẫn muốn thể hiện phong cách cá nhân. Dưới đây là mô tả chi tiết về sản phẩm:\n1.Thiết kế\n-Màu sắc chủ đạo của giày là Dark Brown (nâu đậm), tạo nên một vẻ ngoài mạnh mẽ và cổ điển. Màu nâu giúp giày dễ dàng phối hợp với nhiều trang phục và thích hợp cho nhiều dịp sử dụng khác nhau, từ đi chơi, đi làm đến các hoạt động thể thao nhẹ.\n-Một số chi tiết nhỏ như màu trắng và đen được sử dụng để làm nổi bật thiết kế và logo, mang lại vẻ đẹp hài hòa, dễ nhìn.\n2.Chất liệu\nGiày được làm từ chất liệu da tổng hợp cao cấp và vải lưới, giúp giày có độ bền cao và khả năng thoáng khí tốt. Chất liệu da mang lại sự chắc chắn và bền bỉ, trong khi phần vải lưới giúp tăng cường sự thoải mái và giảm độ nóng, giữ cho đôi chân luôn khô ráo khi di chuyển.\n3.Thiết kế và kiểu dáng\n-Puma Speedcat OG mang đến một thiết kế retro với kiểu dáng thấp, giúp người sử dụng có thể di chuyển linh hoạt và tự do. Giày có đường nét tối giản, không cầu kỳ nhưng rất tinh tế, dễ dàng phối hợp với nhiều phong cách thời trang khác nhau.\n-Thiết kế dây giày cổ điển giúp dễ dàng điều chỉnh vừa vặn, mang lại cảm giác thoải mái cho đôi chân.\n4.Phong cách\nVới thiết kế tối giản và màu sắc trang nhã, Puma Speedcat OG ‘Dark Brown’ mang đậm phong cách thể thao cổ điển nhưng vẫn giữ được vẻ thanh lịch, phù hợp với nhiều hoàn cảnh và hoạt động khác nhau. Đây là một đôi giày lý tưởng cho những ai yêu thích sự thoải mái, dễ phối đồ nhưng không kém phần thời trang.",
    sku: "RF-1027-PUM",
    material: "Da tổng hợp và vải lưới",
  },

  {
    id: "P1028",
    name: "Vans Old Skool OG LX Black White",
    brand: "Vans",
    category: "Lifestyle",
    price: 2900000,
    oldPrice: 3625000,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 39, 41, 42, 43, 44],
    rating: 4.6,
    reviews: 172,
    isNew: false,
    onSale: true,
    stock: 4,
    gender: "Men",
    image: "../../img/Vans Old Skool OG LX Black White/1.png",
    gallery: [
      "../../img/Vans Old Skool OG LX Black White/1.png",
      "../../img/Vans Old Skool OG LX Black White/2.png",
      "../../img/Vans Old Skool OG LX Black White/3.png",
      "../../img/Vans Old Skool OG LX Black White/4.png",
    ],
    description_en:
      "The Vans Old Skool OG LX Black White from Vans is crafted from suede and canvas fabric, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Vans Old Skool OG LX Black White là một phiên bản nâng cấp của mẫu giày Vans Old Skool cổ điển, nổi bật với sự kết hợp giữa phong cách thời trang đường phố và tính năng thoải mái. Với màu sắc đen trắng tinh tế và chất liệu cao cấp, đôi giày này mang đến một diện mạo retro đầy ấn tượng.\n1.Màu sắc\nBlack White (Đen – Trắng): Màu sắc cổ điển của đôi giày với sự kết hợp giữa đen và trắng, tạo ra vẻ ngoài mạnh mẽ, dễ dàng phối hợp với nhiều loại trang phục khác nhau. Màu đen tạo cảm giác mạnh mẽ, trong khi trắng mang lại sự sáng sủa và tươi mới, kết hợp với nhau tạo nên phong cách thời trang tối giản và thanh lịch.\n2.Chất liệu\n-Upper (phần trên của giày) được làm từ da lộn và vải canvas chất lượng cao, giúp giày bền bỉ và thoáng khí. Chất liệu da lộn mang lại vẻ đẹp sang trọng và độ bền cao, trong khi vải canvas tạo sự thoải mái và khả năng lưu thông không khí cho đôi chân.\n-Đế giày làm từ cao su với thiết kế đặc trưng của Vans, với họa tiết waffle giúp tăng độ bám và ổn định khi di chuyển. Đế cao su cũng tạo cảm giác êm ái khi đi lâu dài.\n3.Thiết kế\n-Logo Vans đặc trưng được in trên mặt bên giày, giúp dễ dàng nhận diện thương hiệu.\n-Dây giày thiết kế đơn giản, dễ dàng điều chỉnh để có độ vừa vặn phù hợp với bàn chân của người sử dụng.\n-Đường may tỉ mỉ, chắc chắn và tinh tế, mang lại cảm giác bền vững và chắc chắn cho đôi giày.\n4. Phong cách và ứng dụng:\nGiày Vans Old Skool OG LX Black White rất phù hợp với các hoạt động đường phố, dạo phố, hoặc cho những ai yêu thích phong cách streetwear. Đây là một mẫu giày dễ dàng phối hợp với nhiều trang phục, từ áo thun, quần jeans, đến quần jogger hay shorts.\nVới thiết kế cổ điển, đôi giày này cũng rất phù hợp cho các bạn yêu thích phong cách retro và muốn tạo điểm nhấn trong bộ trang phục của mình.",
    sku: "RF-1028-VAN",
    material: "Da lộn và vải canvas",
  },

  {
    id: "P1029",
    name: "Vans Style 36 Decon SF",
    brand: "Vans",
    category: "Lifestyle",
    price: 2900000,
    oldPrice: null,
    colors: ["Jet Black", "Cloud White"],
    sizes: [38, 40, 41, 42, 43],
    rating: 4.3,
    reviews: 195,
    isNew: false,
    onSale: false,
    stock: 19,
    gender: "Unisex",
    image: "../../img/Vans Style 36 Decon SF/1.png",
    gallery: [
      "../../img/Vans Style 36 Decon SF/1.png",
      "../../img/Vans Style 36 Decon SF/2.png",
      "../../img/Vans Style 36 Decon SF/3.png",
      "../../img/Vans Style 36 Decon SF/4.png",
    ],
    description_en:
      "The Vans Style 36 Decon SF from Vans is crafted from premium fabric, built for everyday wear with a clean, versatile silhouette in Black/White.",
    description_vi:
      "Giày Vans Style 36 Decon SF là một phiên bản của dòng giày Vans Old Skool, với thiết kế đơn giản, năng động và sự kết hợp màu sắc giữa đen và trắng, tạo nên một phong cách cổ điển và hiện đại.\n1.Chất liệu: \nĐôi giày được làm từ chất liệu da tổng hợp hoặc da thật, tùy thuộc vào phiên bản cụ thể, tạo nên sự bền bỉ và độ bền cho đôi giày.\n2.Kiểu dáng: \nĐôi giày có kiểu dáng low-top (thấp) với phần thân giày được cắt đơn giản và phối màu đặc trưng của dòng giày Vans Old Skool.\n3.Màu sắc: \nGiày có màu sắc chủ đạo là màu đen (Black) trên phần thân giày và màu trắng (White) trên phần đế giày, tạo nên sự tương phản nổi bật và cổ điển.\n4.Đế giày: \nĐế giày cao su với thiết kế gân sóng truyền thống của Vans, mang lại độ bám tốt và cảm giác thoải mái khi mi chuyển.\n5.Phong cách\nĐôi giày Vans Style 36 Decon SF  lại lựa chọn phù hợp cho những người yêu thích phong cách đường phố và thích sự kết hợp màu sắc đơn giản nhưng tinh tế. Đôi giày này dễ dàng kết hợp với nhiều trang phục khác nhau và là một điểm nhấn thời trang trong bộ sưu tập giày của bạn. Bạn có thể mang đôi giày này trong nhiều dịp khác nhau, từ dạo phố, hẹn hò, đến các hoạt động thể thao nhẹ, và luôn tự tin với phong cách cá nhân của riêng mình.",
    sku: "RF-1029-VAN",
    material: "Vải cao cấp",
  },
];

function rfFormatVND(n) {
  return n.toLocaleString("vi-VN") + "đ";
}

function rfGetProduct(id) {
  return RF_PRODUCTS.find((p) => p.id === id);
}
